[package]
name = "gql-sema"
description = "Binding, catalog resolution, and type checking for GQL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gql-ast.workspace = true
gql-catalog.workspace = true
gql-ir.workspace = true
gql-source.workspace = true


[build-dependencies]
gql-rust-project-harness-policy.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "performance_verification"
harness = false

[lints]
workspace = true
