;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; MRR-owned session and wire bridge to the generic POO modules/search-engine.
(import (only-in :std/list/list every)
        (only-in :clan/poo/object .ref)
        :poo-flow/modules/search-engine/interface
        (only-in :poo-flow/modules/temporal-causality/objects
                 poo-flow-temporal-observation poo-flow-causal-event)
        (only-in :poo-flow/src/ffi/scheme-wire scheme-wire-read scheme-wire-write)
        (only-in ./projection mrr-search-build-strategy mrr-search-compile-strategy))
(export mrr-search-controller-call)
(def sessions (make-hash-table))
(def (text? value) (and (string? value) (> (string-length value) 0)))
(def (event->wire event)
  (list (.ref event 'identity) (.ref event 'subject)
        (symbol->string (.ref event 'event-kind))
        (.ref (.ref event 'observation) 'provenance-identity)
        (.ref (.ref event 'observation) 'logical-position)
        (.ref event 'payload-identity) (.ref event 'causal-parent-identities)
        (symbol->string (.ref event 'modality)) (.ref event 'committed?)))
(def (wire->event row)
  (unless (and (list? row) (= (length row) 9)
               (every text? (list (car row) (cadr row) (caddr row) (cadddr row)
                                 (list-ref row 5) (list-ref row 7)))
               (integer? (list-ref row 4)) (>= (list-ref row 4) 0)
               (list? (list-ref row 6)) (every text? (list-ref row 6))
               (boolean? (list-ref row 8)))
    (error "invalid Temporal observation wire value"))
  (poo-flow-causal-event
   (car row) (cadr row) (string->symbol (caddr row))
   (poo-flow-temporal-observation (string-append (car row) ":observation")
                                'logical-version (list-ref row 4) (cadddr row))
   (list-ref row 5) (list-ref row 6) (string->symbol (list-ref row 7))
   (list-ref row 8)))
(def (mrr-search-controller-call payload)
  (let (row (scheme-wire-read payload))
    (unless (and (list? row) (>= (length row) 4)
                 (every text? (list (car row) (cadr row) (caddr row) (cadddr row))))
      (error "invalid Search controller request"))
    (let* ((command (car row)) (key (cadr row)) (generation (caddr row))
           (configuration (cadddr row)) (arguments (list-tail row 4))
           (commit #f)
           (bounded (lambda (value)
                      (unless (<= (u8vector-length (string->utf8
                                  (scheme-wire-write (list "mrr.poo.search.engine.v1" key generation configuration value)))) 1048576)
                        (error "Search controller output bound")) value))
           (answer
            (if (or (equal? command "start") (equal? command "start-evidence"))
              (begin
                (unless (and (= (length arguments) 3) (< (hash-length sessions) 64)
                             (not (hash-get sessions key)))
                  (error "Search controller session bound or duplicate identity"))
                (let* ((plan (list (car arguments) generation (cadr arguments)))
                       (strategy (mrr-search-build-strategy plan))
                       (initial (poo-flow-search-engine strategy generation configuration (caddr arguments)))
                       (engine (if (equal? command "start-evidence")
                                 (poo-flow-search-engine-require-evidence initial) initial))
                       (projection (mrr-search-compile-strategy strategy generation))
                       (result (list (scheme-wire-write projection) (map symbol->string (poo-flow-search-engine-frontier engine)))))
                  (bounded result)
                  (set! commit (lambda () (hash-put! sessions key (list generation configuration engine))))
                  result))
              (let (session (hash-get sessions key))
                (unless (and session (equal? generation (car session))
                             (equal? configuration (cadr session)))
                  (error "foreign or released Search controller"))
                (let* ((engine (caddr session))
                       (frontier (lambda (next) (map symbol->string (poo-flow-search-engine-frontier next))))
                       (save (lambda (next) (let (result (bounded (frontier next)))
                                               (set! commit (lambda () (hash-put! sessions key (list generation configuration next)))) result))))
                  (cond
                   ((equal? command "frontier")
                    (unless (null? arguments) (error "invalid frontier request")) (frontier engine))
                   ((equal? command "release")
                    (unless (null? arguments) (error "invalid release request"))
                    (set! commit (lambda () (hash-remove! sessions key))) '())
                   ((equal? command "revise")
                    (unless (and (= (length arguments) 2) (list? (car arguments))
                                 (every text? (car arguments)) (text? (cadr arguments)))
                      (error "invalid revision request"))
                    (save (poo-flow-search-engine-revise engine (map string->symbol (car arguments)) (cadr arguments))))
                   ((equal? command "issue")
                    (unless (and (= (length arguments) 1) (text? (car arguments)))
                      (error "invalid issue request"))
                    (let* ((issued (poo-flow-search-engine-issue engine (string->symbol (car arguments))))
                           (request (.ref issued 'request))
                           (result (list (car arguments) (.ref request 'source-cut)
                                         (.ref request 'revision) (.ref request 'attempt))))
                      (bounded result)
                      (save (.ref issued 'engine)) result))
                   ((member command '("complete" "cancel" "observe" "inputs"))
                    (unless (and (= (length arguments) (if (equal? command "observe") 5 4))
                                 (text? (car arguments)) (text? (cadr arguments))
                                 (every (lambda (n) (and (integer? n) (>= n 0)))
                                        (list (caddr arguments) (cadddr arguments))))
                      (error "invalid completion identity"))
                    (let* ((name (string->symbol (car arguments)))
                           (node (poo-flow-search-engine-node engine name))
                           (request (poo-flow-search-attempt-request (.ref node 'state)
                                       (cadr arguments) (caddr arguments) (cadddr arguments))))
                      (cond
                       ((equal? command "cancel")
                        (save (poo-flow-search-engine-cancel engine name request)))
                       ((equal? command "observe")
                        (save (poo-flow-search-engine-observe engine name request
                                (wire->event (list-ref arguments 4)))))
                       ((equal? command "inputs")
                        (unless (and (.ref engine 'evidence-required?)
                                     (poo-flow-search-attempt-current? (.ref node 'state) request))
                          (error "foreign, stale or identity-only Search inputs"))
                        (map (lambda (parent)
                               (let (event (.ref (poo-flow-search-engine-node engine parent) 'evidence))
                                 (unless event (error "missing Search predecessor evidence"))
                                 (event->wire event)))
                             (.ref node 'dependencies)))
                       (else (save (poo-flow-search-engine-complete engine name request))))))
                   (else (error "unknown Search controller command"))))))))
      ;; Encode once before mutation. Native publication only retains these bytes.
      (let (bytes (string->utf8 (scheme-wire-write
                                (list "mrr.poo.search.engine.v1" key generation configuration answer))))
        (unless (<= (u8vector-length bytes) 1048576) (error "Search controller output bound"))
        (when commit (commit))
        bytes))))
