[pytest]
testpaths = proofs/MRRProof/tests
norecursedirs =
    .data
    .devenv
    .direnv
    .git
    .venv
    build
    dist
    node_modules
    target
addopts = --strict-config --strict-markers
