# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

[pytest]
testpaths = proofs/MRRProof/tests
norecursedirs =
    .data
    .devenv
    .direnv
    .git
    .venv
    build
    dist
    node_modules
    target
addopts = --strict-config --strict-markers
