# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

version = 1

[[annotations]]
path = [
  "LICENSE",
  "**/LICENSE",
  "LICENSES/**",
  "*.lock",
  "**/*.lock",
  "*.json",
  "**/*.json",
  "**/*.gql",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 tao3k team and Contributors"
SPDX-License-Identifier = "AGPL-3.0-only"
