[package]
name = "gql-syntax"
description = "Lossless syntax foundation for ISO GQL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gql-source.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true
