;;; Single-source property-graph query declaration consumed by every POO
;;; language profile and by the native AOT ABI owner.

(defsyntax (with-mrr-gql-declaration stx)
  (syntax-case stx ()
    ((_ consumer grammar-binding dialect-id dialect-label)
     #'(consumer grammar-binding
         (dialect dialect-id dialect-label #t)
         (extends)
         (syntax-kinds
          (SourceFile node (query))
          (Query node (clause))
          (MatchClause node (pattern))
          (WhereClause node (expression))
          (LetClause node (binding expression))
          (ReturnClause node (projection))
          (GraphPattern node (element))
          (NodePattern node (binding labels properties))
          (PropertyMap node (entry))
          (PropertyEntry node (key value))
          (EdgePattern node (direction binding labels properties quantifier))
          (LabelList node (label))
          (Expression node (token))
          (NameExpression node (name))
          (LiteralExpression node (literal))
          (UnaryExpression node (operator operand))
          (BinaryExpression node (left operator right))
          (ParenthesizedExpression node (expression))
          (Keyword token (text))
          (Identifier token (text))
          (Number token (text))
          (String token (text))
          (Whitespace token (text))
          (Punctuation token (text))
          (Comment token (text))
          (Unknown token (text))
          (PropertyAccessExpression node (base property))
          (PathPattern node (binding pattern))
          (PathQuantifier node (minimum maximum))
          (OptionalMatchClause node (match))
          (ListExpression node (element))
          (SubscriptExpression node (base index))
          (ProjectionAlias node (expression alias))
          (UnionClause node (query))
          (LimitClause node (limit))
          (OrderByClause node (key direction))
          (OffsetClause node (offset))
          (CaseExpression node (operand branch else-result))
          (CaseWhenClause node (condition result))
          (CaseElseClause node (result)))
         (keywords
          (Match "MATCH") (Optional "OPTIONAL") (Where "WHERE") (Let "LET")
          (Return "RETURN") (Or "OR") (And "AND") (Not "NOT") (Call "CALL")
          (Create "CREATE") (Drop "DROP") (Insert "INSERT") (Delete "DELETE")
          (Set "SET") (Remove "REMOVE") (True "TRUE") (False "FALSE")
          (Null "NULL") (In "IN") (As "AS") (Union "UNION") (Limit "LIMIT")
          (Order "ORDER") (By "BY") (Asc "ASC") (Desc "DESC")
          (Offset "OFFSET") (Case "CASE") (When "WHEN") (Then "THEN")
          (Else "ELSE") (End "END"))
         (prefix-operators ((keyword Not) 25 right))
         (binary-operators
          ((keyword Or) 10 left) ((keyword And) 20 left)
          ((keyword In) 30 left)
          ((punctuation "=") 30 left) ((punctuation "!=") 30 left)
          ((punctuation "<") 30 left) ((punctuation "<=") 30 left)
          ((punctuation ">") 30 left) ((punctuation ">=") 30 left)
          ((punctuation "+") 40 left) ((punctuation "-") 40 left)
          ((punctuation "*") 50 left) ((punctuation "/") 50 left)
          ((punctuation "%") 50 left))
         (parser-entrypoints
          (Match MatchClause marks-match)
          (Optional OptionalMatchClause marks-match)
          (Return ReturnClause marks-return)
          (Where WhereClause none) (Let LetClause none)
          (Union UnionClause none) (Limit LimitClause none)
          (Order OrderByClause none) (Offset OffsetClause none)
          (Call UnsupportedStatement none) (Create UnsupportedStatement none)
          (Drop UnsupportedStatement none) (Insert UnsupportedStatement none)
          (Delete UnsupportedStatement none) (Set UnsupportedStatement none)
          (Remove UnsupportedStatement none))
         (recoveries
          (unsupported-statement "GQL-PARSE-UNSUPPORTED-STATEMENT" preserve-source)
          (unsupported-keyword-expression
           "GQL-PARSE-UNSUPPORTED-KEYWORD-EXPRESSION" preserve-source)
          (expression-syntax "GQL-PARSE-EXPRESSION-SYNTAX" preserve-source))))))
