;;; Single-source property-graph query declaration consumed by every POO
;;; language profile and by the native AOT ABI owner.

(export with-mrr-gql-declaration)

(defsyntax (with-mrr-gql-declaration stx)
  (syntax-case stx ()
    ((_ consumer grammar-binding dialect-id dialect-label)
     #'(consumer grammar-binding
         (dialect dialect-id dialect-label #t)
         (extends)
         (syntax-kinds
          (SourceFile node (query))
          (Query node (clause))
          (MatchClause node (mode patterns))
          (WhereClause node (expression))
          (LetClause node (binding))
          (LetBinding node (name value))
          (ReturnClause node (projection))
          (GraphPattern node (element))
          (GraphPatternList node (pattern))
          (NodePattern node (binding labels properties predicate))
          (PropertyMap node (entry))
          (PropertyEntry node (key value))
          (EdgePattern node (direction binding labels properties predicate quantifier))
          (LabelList node (label))
          (Expression node (token))
          (NameExpression node (name))
          (LiteralExpression node (literal))
          (CharacterStringLiteralExpression node (value form no-escape))
          (UnaryExpression node (operator operand))
          (BinaryExpression node (left operator right))
          (ParenthesizedExpression node (expression))
          (Keyword token (text))
          (Identifier token (text))
          (Number token (text))
          (String token (text))
          (ByteString token (text))
          (Whitespace token (text))
          (Punctuation token (text))
          (Comment token (text))
          (Unknown token (text))
          (PropertyAccessExpression node (base property))
          (FunctionCallExpression node (name argument))
          (PathPattern node (binding pattern))
          (PathMode node (kind))
          (PathQuantifier node (minimum maximum))
          (OptionalMatchClause node (match))
          (ListExpression node (element))
          (ByteStringLiteralExpression node (value))
          (TemporalLiteralExpression node (qualifier value))
          (DurationLiteralExpression node (value))
          (RecordExpression node (entry))
          (RecordEntry node (name value))
          (SubscriptExpression node (base index))
          (ProjectionAlias node (expression alias))
          (UnionClause node (query))
          (LimitClause node (limit))
          (OrderByClause node (key direction))
          (OffsetClause node (offset))
          (GroupByClause node (key))
          (CaseExpression node (operand branch else-result))
          (CaseWhenClause node (condition result))
          (CaseElseClause node (result))
          (CreateSchemaStatement node (name))
          (DropSchemaStatement node (name))
          (CreateGraphStatement node (name graph-type))
          (DropGraphStatement node (name))
          (CreateGraphTypeStatement node (name source policy))
          (DropGraphTypeStatement node (name policy))
          (CatalogObjectName node (part))
          (CatalogConflictClause node (kind))
          (GraphTypeSource node (kind target))
          (NestedGraphTypeSpecification node (element))
        (NodeTypeSpecification node (name alias key-labels labels properties))
        (EdgeTypeSpecification node (kind name endpoints direction key-labels labels properties))
        (EdgeKind node (kind))
        (EndpointPair node (endpoints direction))
        (NodeTypeReference node (alias key-labels labels properties))
        (EdgeDirection node (kind))
        (KeyLabelSet node (labels))
        (LabelSetPhrase node (labels))
          (PropertyTypeList node (property))
          (PropertyType node (name marker value-type))
          (PropertyValueType node (form item bound field nullability))
          (ValueTypeAtom node (kind parameter item field))
          (ReferenceValueType node (kind openness property specification field))
          (TypeParameterList node (value))
          (FieldTypeList node (field))
          (FieldType node (name marker value-type))
          (NotNullConstraint node (kind))
          (InsertStatement node (pattern))
          (SetStatement node (item))
          (SetItem node (target value))
          (RemoveStatement node (item))
          (RemoveItem node (target))
          (DeleteStatement node (item detach))
          (DeleteItem node (target))
          (CallStatement node (call))
          (ProcedureName node (part))
          (StartTransactionStatement node (access-mode))
          (CommitStatement node (action))
          (RollbackStatement node (action))
          (SessionSetStatement node (setting))
          (SessionResetStatement node (setting))
          (SessionCloseStatement node (action))
          (InlineWhereClause node (expression))
          (LabelPredicateExpression node (operand label))
          (LabelNameExpression node (name))
          (LabelWildcardExpression node (wildcard))
          (LabelNotExpression node (operand))
          (LabelAndExpression node (left right))
          (LabelOrExpression node (left right)))
         (keywords
          (Match "MATCH") (Optional "OPTIONAL") (Where "WHERE") (Let "LET")
          (Return "RETURN") (Or "OR") (Xor "XOR") (And "AND") (Not "NOT")
          (Call "CALL")
          (Create "CREATE") (Drop "DROP") (Insert "INSERT") (Delete "DELETE")
          (Set "SET") (Remove "REMOVE") (True "TRUE") (False "FALSE")
          (Null "NULL") (In "IN") (As "AS") (Union "UNION") (Limit "LIMIT")
          (Order "ORDER") (By "BY") (Group "GROUP") (Asc "ASC") (Desc "DESC")
          (Offset "OFFSET") (Case "CASE") (When "WHEN") (Then "THEN")
          (Else "ELSE") (End "END") (Schema "SCHEMA")
          (Session "SESSION") (Reset "RESET") (Close "CLOSE")
          (Property "PROPERTY") (Graph "GRAPH") (Any "ANY") (Typed "TYPED")
          (If "IF") (Exists "EXISTS") (Replace "REPLACE") (Type "TYPE")
          (Copy "COPY") (Of "OF") (Like "LIKE")
          (Detach "DETACH") (Nodetach "NODETACH")
          (Start "START") (Transaction "TRANSACTION")
          (Read "READ") (Only "ONLY") (Write "WRITE")
          (Commit "COMMIT") (Rollback "ROLLBACK")
          (Walk "WALK") (Trail "TRAIL") (Acyclic "ACYCLIC")
          (Simple "SIMPLE") (Is "IS") (Labeled "LABELED")
          (Date "DATE") (Time "TIME") (Timestamp "TIMESTAMP")
          (Datetime "DATETIME") (Duration "DURATION") (Record "RECORD"))
         (non-reserved-words
          ACYCLIC BINDING BINDINGS CONNECTING DESTINATION DIFFERENT DIRECTED
          EDGE EDGES ELEMENT ELEMENTS FIRST GRAPH GROUPS KEEP LABEL LABELED
          LABELS LAST NFC NFD NFKC NFKD NO NODE NORMALIZED ONLY ORDINALITY
          PROPERTY READ RELATIONSHIP RELATIONSHIPS REPEATABLE SHORTEST SIMPLE
          SOURCE TABLE TO TRAIL TRANSACTION TYPE UNDIRECTED VERTEX WALK WITHOUT
          WRITE ZONE)
         (numeric-literals
          (exact-scientific scientific M exact)
          (exact-common common M exact)
          (exact-common-unsuffixed common none exact)
          (exact-integer integer M exact)
          (unsigned-integer integer none integer)
          (approximate-scientific scientific FD approximate)
          (approximate-scientific-unsuffixed scientific none approximate)
          (approximate-common common FD approximate)
          (approximate-integer integer FD approximate))
         (character-string-literals
          (single-quoted quote escaped-or-doubled character-string)
          (double-quoted double-quote escaped-or-doubled character-string)
          (no-escape commercial-at preserve-representations raw)
          (escaped-reverse-solidus reverse-solidus decode scalar)
          (escaped-quote quote decode scalar)
          (escaped-double-quote double-quote decode scalar)
          (escaped-grave-accent grave-accent decode scalar)
          (escaped-tab t decode control)
          (escaped-backspace b decode control)
          (escaped-new-line n decode control)
          (escaped-carriage-return r decode control)
          (escaped-form-feed f decode control)
          (escaped-unicode4 u decode four-hex-digits)
          (escaped-unicode6 U decode six-hex-digits))
         (prefix-operators
          ((keyword Not) 25 right)
          ((punctuation "+") 60 right) ((punctuation "-") 60 right))
         (binary-operators
          ((keyword Or) 10 left) ((keyword Xor) 15 left) ((keyword And) 20 left)
          ((keyword In) 30 left)
          ((punctuation "=") 30 left) ((punctuation "<>") 30 left)
          ((punctuation "<") 30 left) ((punctuation "<=") 30 left)
          ((punctuation ">") 30 left) ((punctuation ">=") 30 left)
          ((punctuation "||") 35 left)
          ((punctuation "+") 40 left) ((punctuation "-") 40 left)
          ((punctuation "*") 50 left) ((punctuation "/") 50 left)
          ((punctuation "%") 50 left))
         (parser-entrypoints
          (Match MatchClause marks-match)
          (Optional OptionalMatchClause marks-match)
          (Return ReturnClause marks-return)
          (Where WhereClause none) (Let LetClause none)
          (Union UnionClause none) (Limit LimitClause none)
          (Order OrderByClause none) (Offset OffsetClause none)
          (Group GroupByClause none)
          (Call CallStatement none) (Create CreateSchemaStatement none)
          (Drop DropSchemaStatement none) (Insert InsertStatement none)
          (Delete DeleteStatement none) (Set SetStatement none)
          (Remove RemoveStatement none) (Detach DeleteStatement none)
          (Nodetach DeleteStatement none) (Start StartTransactionStatement none)
          (Commit CommitStatement none) (Rollback RollbackStatement none)
          (Session SessionSetStatement none))
         (recoveries
          (block-comment
           "GQL-SYNTAX-UNTERMINATED-BLOCK-COMMENT" preserve-source)
          (numeric-literal
           "GQL-SYNTAX-INVALID-NUMERIC-LITERAL" preserve-source)
          (integer-literal-range
           "GQL-SYNTAX-NUMERIC-LITERAL-OUT-OF-RANGE" preserve-source)
          (edge-label-separator
           "GQL-PARSE-EDGE-LABEL-SEPARATOR" preserve-source)
          (create-schema
           "GQL-PARSE-CREATE-SCHEMA-SYNTAX" preserve-source)
          (drop-schema
           "GQL-PARSE-DROP-SCHEMA-SYNTAX" preserve-source)
          (create-graph
           "GQL-PARSE-CREATE-GRAPH-SYNTAX" preserve-source)
          (drop-graph
           "GQL-PARSE-DROP-GRAPH-SYNTAX" preserve-source)
          (create-graph-type
           "GQL-PARSE-CREATE-GRAPH-TYPE-SYNTAX" preserve-source)
          (nested-graph-type
           "GQL-PARSE-NESTED-GRAPH-TYPE-SYNTAX" preserve-source)
          (drop-graph-type
           "GQL-PARSE-DROP-GRAPH-TYPE-SYNTAX" preserve-source)
          (insert-statement
           "GQL-PARSE-INSERT-SYNTAX" preserve-source)
          (set-statement
           "GQL-PARSE-SET-SYNTAX" preserve-source)
          (remove-statement
           "GQL-PARSE-REMOVE-SYNTAX" preserve-source)
          (delete-statement
           "GQL-PARSE-DELETE-SYNTAX" preserve-source)
          (call-statement
           "GQL-PARSE-CALL-SYNTAX" preserve-source)
          (transaction-command
           "GQL-PARSE-TRANSACTION-SYNTAX" preserve-source)
          (session-command
           "GQL-PARSE-SESSION-COMMAND-SYNTAX" preserve-source)
          (inline-node-where
           "GQL-PARSE-INLINE-WHERE-SYNTAX" preserve-source)
          (inline-edge-where
           "GQL-PARSE-INLINE-WHERE-SYNTAX" preserve-source)
          (path-mode
           "GQL-PARSE-PATH-MODE-SYNTAX" preserve-source)
          (path-quantifier
           "GQL-PARSE-PATH-QUANTIFIER" preserve-source)
          (string-literal
           "GQL-SYNTAX-UNTERMINATED-STRING" preserve-source)
          (character-string-literal
           "GQL-SYNTAX-INVALID-CHARACTER-STRING-LITERAL" preserve-source)
          (byte-string-literal
           "GQL-SYNTAX-INVALID-BYTE-STRING" preserve-source)
          (temporal-literal
           "GQL-SYNTAX-INVALID-TEMPORAL-LITERAL" preserve-source)
          (duration-literal
           "GQL-SYNTAX-INVALID-DURATION-LITERAL" preserve-source)
          (list-literal
           "GQL-PARSE-LIST-SYNTAX" preserve-source)
          (record-literal
           "GQL-PARSE-RECORD-SYNTAX" preserve-source)
          (delimited-identifier
           "GQL-SYNTAX-UNTERMINATED-DELIMITED-IDENTIFIER" preserve-source)
          (identifier-escape
           "GQL-SYNTAX-INVALID-IDENTIFIER-ESCAPE" preserve-source)
          (binding-variable
           "GQL-PARSE-BINDING-VARIABLE-SYNTAX" preserve-source)
          (unsupported-statement "GQL-PARSE-UNSUPPORTED-STATEMENT" preserve-source)
          (unsupported-keyword-expression
           "GQL-PARSE-UNSUPPORTED-KEYWORD-EXPRESSION" preserve-source)
          (non-iso-operator "GQL-PARSE-NON-ISO-OPERATOR" preserve-source)
          (label-expression "GQL-PARSE-LABEL-EXPRESSION" preserve-source)
          (match-pattern-list "GQL-PARSE-MATCH-PATTERN-LIST" preserve-source)
          (optional-match "GQL-PARSE-OPTIONAL-MATCH-SYNTAX" preserve-source)
          (where-clause "GQL-PARSE-WHERE-SYNTAX" preserve-source)
          (union-clause "GQL-PARSE-UNION-SYNTAX" preserve-source)
          (expression-syntax "GQL-PARSE-EXPRESSION-SYNTAX" preserve-source))))))
