CREATE GRAPH TYPE analytics.reference_and_predefined AS { NODE TYPE Sample { graph_ref PROPERTY GRAPH { NODE TYPE Person (person {name STRING}) }, node_ref NODE TYPE Person {id INT64}, edge_ref EDGE TYPE Knows ({id INT64})-[{since INT64}]->({id INT64}), signed_value SIGNED INTEGER16, unsigned_value UNSIGNED BIG INTEGER, timestamp_value TIMESTAMP WITH TIME ZONE, decimal_value DEC(10, 2) } }
