# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "mrr-query"
description = "Language-neutral query atoms and variables for MRR"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mrr-identity.workspace = true
mrr-relation.workspace = true
serde.workspace = true
ciborium.workspace = true

[dev-dependencies]
criterion.workspace = true
mrr-asp-rust-build-support.workspace = true
[[bench]]
name = "query_perf"
harness = false

[lints]
workspace = true
