[package]
name = "mrr-asp-rust-build-support"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
asp-rust = { git = "https://github.com/tao3k/asp-rust", rev = "2419414ee5379bad89506496e3eaab928df68daf", version = "0.1.2", default-features = false }
asp-rust-build-support = { git = "https://github.com/tao3k/asp-rust", rev = "2419414ee5379bad89506496e3eaab928df68daf", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
criterion = { version = "0.8.2" }

[[test]]
name = "unit_test"
path = "tests/unit_test.rs"

[[bench]]
name = "performance_verification"
harness = false
