# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "mrr-frontends"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
icu_properties.workspace = true
mrr-query.workspace = true
mrr-gerbil.workspace = true
rowan.workspace = true

[dev-dependencies]
criterion.workspace = true
mrr-asp-rust-build-support.workspace = true

[[bench]]
name = "frontend_perf"
harness = false

[lints]
workspace = true
