[package]
name = "mrr-frontends"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gql-ast = { path = "../gql-ast", version = "0.1.0", default-features = false }
gql-source.workspace = true
gql-syntax = { path = "../gql-syntax", version = "0.1.0", default-features = false }
mrr-query.workspace = true
mrr-gerbil.workspace = true
rowan.workspace = true

[build-dependencies]
mrr-asp-rust-project-policy.workspace = true

[dev-dependencies]
criterion.workspace = true
gql-ast = { path = "../gql-ast", version = "0.1.0", features = ["syntax-lowering"] }
gql-syntax.workspace = true

[[bench]]
name = "frontend_perf"
harness = false

[lints]
workspace = true
