-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [meta_relational_reasoning]: function definitions
module
public import Aeneas
public import TransformGenerated.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace MRR.TransformationRust

/-- [meta_relational_reasoning::transformation_table::forward]:
    Source: 'crates/meta-relational-reasoning/src/transformation_table.rs', lines 10:0-15:1 -/
def transformation_table.forward
  (table : Slice Std.Usize) (input : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let o <-
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.Usize)
      table input
  match o with
  | none => ok none
  | some _ => ok o

/-- [meta_relational_reasoning::transformation_table::solve]:
    Source: 'crates/meta-relational-reasoning/src/transformation_table.rs', lines 17:0-22:1 -/
def transformation_table.solve
  (table : Slice (alloc.vec.Vec Std.Usize)) (input : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let o <-
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
      Std.Usize)) table input
  match o with
  | none => ok none
  | some row =>
    let s := alloc.vec.Vec.deref row
    transformation_table.forward s 0#usize

/-- [meta_relational_reasoning::transformation_table::extract]:
    Source: 'crates/meta-relational-reasoning/src/transformation_table.rs', lines 24:0-29:1 -/
def transformation_table.extract
  (table : Slice (alloc.vec.Vec Std.Usize)) (input : Std.Usize)
  (answer : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let o <-
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
      Std.Usize)) table input
  match o with
  | none => ok none
  | some row =>
    let s := alloc.vec.Vec.deref row
    transformation_table.forward s answer

end MRR.TransformationRust
