MATCH (identifierRoot {`\u203f`: 1, @`raw\n`: 2}), (ACYCLIC), (BINDING), (BINDINGS), (CONNECTING), (DESTINATION), (DIFFERENT), (DIRECTED), (EDGE), (EDGES), (ELEMENT), (ELEMENTS), (FIRST), (GRAPH), (GROUPS), (KEEP), (LABEL), (LABELED), (LABELS), (LAST), (NFC), (NFD), (NFKC), (NFKD), (NO), (NODE), (NORMALIZED), (ONLY), (ORDINALITY), (PROPERTY), (READ), (RELATIONSHIP), (RELATIONSHIPS), (REPEATABLE), (SHORTEST), (SIMPLE), (SOURCE), (TABLE), (TO), (TRAIL), (TRANSACTION), (TYPE), (UNDIRECTED), (VERTEX), (WALK), (WITHOUT), (WRITE), (ZONE) RETURN identifierRoot, ACYCLIC, BINDING, BINDINGS, CONNECTING, DESTINATION, DIFFERENT, DIRECTED, EDGE, EDGES, ELEMENT, ELEMENTS, FIRST, GRAPH, GROUPS, KEEP, LABEL, LABELED, LABELS, LAST, NFC, NFD, NFKC, NFKD, NO, NODE, NORMALIZED, ONLY, ORDINALITY, PROPERTY, READ, RELATIONSHIP, RELATIONSHIPS, REPEATABLE, SHORTEST, SIMPLE, SOURCE, TABLE, TO, TRAIL, TRANSACTION, TYPE, UNDIRECTED, VERTEX, WALK, WITHOUT, WRITE, ZONE
