[package]
name = "gql-ast"
description = "Pure ISO GQL abstract syntax model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gql-source.workspace = true
gql-syntax.workspace = true

[dev-dependencies]
asp-rust-build-support.workspace = true
criterion.workspace = true
[build-dependencies]
mrr-asp-rust-project-policy.workspace = true

[[bench]]
name = "ast_perf"
harness = false

[lints]
workspace = true
