[package]
name = "gql-ast"
description = "Pure ISO GQL abstract syntax model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gql-source.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true
