// mrr.gerbil-grammar-projection.v1 input-sha256=29ca6a1dd3399fa9232c57c2a871ca755ad919907da1e59241c34caaeaa52535 body-sha256=088c4d3924388164c443cd0636524a1c733206f9faf26a0b79ec7fd39f1f47ea gerbil-scheme-rust-rev=a83fb649ddbbeaabdb538a6eaf0ded10838f7fad
// Generated through the Gerbil native AOT bindings; do not edit.
//! Property-graph grammar projection consumed by the Rowan CST frontend.
use crate::syntax::TokenKind;
pub(crate) const GRAMMAR_PROJECTION_SCHEMA: &str = "mrr.gerbil-grammar-projection.v1";
pub(crate) const GERBIL_SCHEME_RUST_REVISION: &str = "a83fb649ddbbeaabdb538a6eaf0ded10838f7fad";
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Ord, PartialOrd)]
#[repr(u16)]
/// Grammar-owned lossless Rowan syntax kinds.
pub enum SyntaxKind {
    SourceFile,
    Query,
    MatchClause,
    WhereClause,
    LetClause,
    LetBinding,
    ReturnClause,
    GraphPattern,
    GraphPatternList,
    NodePattern,
    PropertyMap,
    PropertyEntry,
    EdgePattern,
    LabelList,
    Expression,
    NameExpression,
    LiteralExpression,
    CharacterStringLiteralExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression,
    Keyword,
    Identifier,
    Number,
    String,
    ByteString,
    Whitespace,
    Punctuation,
    Comment,
    Unknown,
    PropertyAccessExpression,
    FunctionCallExpression,
    PathPattern,
    PathMode,
    PathQuantifier,
    OptionalMatchClause,
    ListExpression,
    ByteStringLiteralExpression,
    TemporalLiteralExpression,
    DurationLiteralExpression,
    RecordExpression,
    RecordEntry,
    SubscriptExpression,
    ProjectionAlias,
    UnionClause,
    LimitClause,
    OrderByClause,
    OffsetClause,
    GroupByClause,
    CaseExpression,
    CaseWhenClause,
    CaseElseClause,
    CreateSchemaStatement,
    DropSchemaStatement,
    CreateGraphStatement,
    DropGraphStatement,
    CreateGraphTypeStatement,
    DropGraphTypeStatement,
    CatalogObjectName,
    CatalogConflictClause,
    GraphTypeSource,
    NestedGraphTypeSpecification,
    NodeTypeSpecification,
    EdgeTypeSpecification,
    EdgeKind,
    EndpointPair,
    NodeTypeReference,
    EdgeDirection,
    KeyLabelSet,
    LabelSetPhrase,
    PropertyTypeList,
    PropertyType,
    PropertyValueType,
    ValueTypeAtom,
    ReferenceValueType,
    TypeParameterList,
    FieldTypeList,
    FieldType,
    NotNullConstraint,
    InsertStatement,
    SetStatement,
    SetItem,
    RemoveStatement,
    RemoveItem,
    DeleteStatement,
    DeleteItem,
    CallStatement,
    ProcedureName,
    StartTransactionStatement,
    CommitStatement,
    RollbackStatement,
    SessionSetStatement,
    SessionResetStatement,
    SessionCloseStatement,
    InlineWhereClause,
    LabelPredicateExpression,
    LabelNameExpression,
    LabelWildcardExpression,
    LabelNotExpression,
    LabelAndExpression,
    LabelOrExpression,
}
/// ISO GQL non-reserved words admitted as regular identifiers.
pub const ISO_GQL_NON_RESERVED_WORDS: &str = "ACYCLIC BINDING BINDINGS CONNECTING DESTINATION DIFFERENT DIRECTED EDGE EDGES ELEMENT ELEMENTS FIRST GRAPH GROUPS KEEP LABEL LABELED LABELS LAST NFC NFD NFKC NFKD NO NODE NORMALIZED ONLY ORDINALITY PROPERTY READ RELATIONSHIP RELATIONSHIPS REPEATABLE SHORTEST SIMPLE SOURCE TABLE TO TRAIL TRANSACTION TYPE UNDIRECTED VERTEX WALK WITHOUT WRITE ZONE";
/// Returns whether `word` is an ISO GQL non-reserved word.
pub fn is_non_reserved_word(word: &str) -> bool {
    ISO_GQL_NON_RESERVED_WORDS
        .split_ascii_whitespace()
        .any(|candidate| word.eq_ignore_ascii_case(candidate))
}
/// Gerbil-owned ISO GQL numeric literal forms: form, notation, suffix, semantic class.
pub const ISO_GQL_NUMERIC_LITERAL_FORMS: &[(&str, &str, &str, &str)] = &[
    ("exact-scientific", "scientific", "M", "exact"),
    ("exact-common", "common", "M", "exact"),
    ("exact-common-unsuffixed", "common", "none", "exact"),
    ("exact-integer", "integer", "M", "exact"),
    ("unsigned-integer", "integer", "none", "integer"),
    ("approximate-scientific", "scientific", "FD", "approximate"),
    (
        "approximate-scientific-unsuffixed",
        "scientific",
        "none",
        "approximate",
    ),
    ("approximate-common", "common", "FD", "approximate"),
    ("approximate-integer", "integer", "FD", "approximate"),
];
/// Gerbil-owned character-string forms and escape actions.
pub const ISO_GQL_CHARACTER_STRING_FORMS: &[(&str, &str, &str, &str)] = &[
    (
        "single-quoted",
        "quote",
        "escaped-or-doubled",
        "character-string",
    ),
    (
        "double-quoted",
        "double-quote",
        "escaped-or-doubled",
        "character-string",
    ),
    (
        "no-escape",
        "commercial-at",
        "preserve-representations",
        "raw",
    ),
    (
        "escaped-reverse-solidus",
        "reverse-solidus",
        "decode",
        "scalar",
    ),
    ("escaped-quote", "quote", "decode", "scalar"),
    ("escaped-double-quote", "double-quote", "decode", "scalar"),
    ("escaped-grave-accent", "grave-accent", "decode", "scalar"),
    ("escaped-tab", "t", "decode", "control"),
    ("escaped-backspace", "b", "decode", "control"),
    ("escaped-new-line", "n", "decode", "control"),
    ("escaped-carriage-return", "r", "decode", "control"),
    ("escaped-form-feed", "f", "decode", "control"),
    ("escaped-unicode4", "u", "decode", "four-hex-digits"),
    ("escaped-unicode6", "U", "decode", "six-hex-digits"),
];
impl SyntaxKind {
    pub const ALL: &'static [Self] = &[
        Self::SourceFile,
        Self::Query,
        Self::MatchClause,
        Self::WhereClause,
        Self::LetClause,
        Self::LetBinding,
        Self::ReturnClause,
        Self::GraphPattern,
        Self::GraphPatternList,
        Self::NodePattern,
        Self::PropertyMap,
        Self::PropertyEntry,
        Self::EdgePattern,
        Self::LabelList,
        Self::Expression,
        Self::NameExpression,
        Self::LiteralExpression,
        Self::CharacterStringLiteralExpression,
        Self::UnaryExpression,
        Self::BinaryExpression,
        Self::ParenthesizedExpression,
        Self::Keyword,
        Self::Identifier,
        Self::Number,
        Self::String,
        Self::ByteString,
        Self::Whitespace,
        Self::Punctuation,
        Self::Comment,
        Self::Unknown,
        Self::PropertyAccessExpression,
        Self::FunctionCallExpression,
        Self::PathPattern,
        Self::PathMode,
        Self::PathQuantifier,
        Self::OptionalMatchClause,
        Self::ListExpression,
        Self::ByteStringLiteralExpression,
        Self::TemporalLiteralExpression,
        Self::DurationLiteralExpression,
        Self::RecordExpression,
        Self::RecordEntry,
        Self::SubscriptExpression,
        Self::ProjectionAlias,
        Self::UnionClause,
        Self::LimitClause,
        Self::OrderByClause,
        Self::OffsetClause,
        Self::GroupByClause,
        Self::CaseExpression,
        Self::CaseWhenClause,
        Self::CaseElseClause,
        Self::CreateSchemaStatement,
        Self::DropSchemaStatement,
        Self::CreateGraphStatement,
        Self::DropGraphStatement,
        Self::CreateGraphTypeStatement,
        Self::DropGraphTypeStatement,
        Self::CatalogObjectName,
        Self::CatalogConflictClause,
        Self::GraphTypeSource,
        Self::NestedGraphTypeSpecification,
        Self::NodeTypeSpecification,
        Self::EdgeTypeSpecification,
        Self::EdgeKind,
        Self::EndpointPair,
        Self::NodeTypeReference,
        Self::EdgeDirection,
        Self::KeyLabelSet,
        Self::LabelSetPhrase,
        Self::PropertyTypeList,
        Self::PropertyType,
        Self::PropertyValueType,
        Self::ValueTypeAtom,
        Self::ReferenceValueType,
        Self::TypeParameterList,
        Self::FieldTypeList,
        Self::FieldType,
        Self::NotNullConstraint,
        Self::InsertStatement,
        Self::SetStatement,
        Self::SetItem,
        Self::RemoveStatement,
        Self::RemoveItem,
        Self::DeleteStatement,
        Self::DeleteItem,
        Self::CallStatement,
        Self::ProcedureName,
        Self::StartTransactionStatement,
        Self::CommitStatement,
        Self::RollbackStatement,
        Self::SessionSetStatement,
        Self::SessionResetStatement,
        Self::SessionCloseStatement,
        Self::InlineWhereClause,
        Self::LabelPredicateExpression,
        Self::LabelNameExpression,
        Self::LabelWildcardExpression,
        Self::LabelNotExpression,
        Self::LabelAndExpression,
        Self::LabelOrExpression,
    ];
    pub(crate) fn to_rowan(self) -> rowan::SyntaxKind {
        rowan::SyntaxKind(self as u16)
    }
    pub(crate) fn from_rowan(kind: rowan::SyntaxKind) -> Self {
        match kind.0 {
            0 => Self::SourceFile,
            1 => Self::Query,
            2 => Self::MatchClause,
            3 => Self::WhereClause,
            4 => Self::LetClause,
            5 => Self::LetBinding,
            6 => Self::ReturnClause,
            7 => Self::GraphPattern,
            8 => Self::GraphPatternList,
            9 => Self::NodePattern,
            10 => Self::PropertyMap,
            11 => Self::PropertyEntry,
            12 => Self::EdgePattern,
            13 => Self::LabelList,
            14 => Self::Expression,
            15 => Self::NameExpression,
            16 => Self::LiteralExpression,
            17 => Self::CharacterStringLiteralExpression,
            18 => Self::UnaryExpression,
            19 => Self::BinaryExpression,
            20 => Self::ParenthesizedExpression,
            21 => Self::Keyword,
            22 => Self::Identifier,
            23 => Self::Number,
            24 => Self::String,
            25 => Self::ByteString,
            26 => Self::Whitespace,
            27 => Self::Punctuation,
            28 => Self::Comment,
            29 => Self::Unknown,
            30 => Self::PropertyAccessExpression,
            31 => Self::FunctionCallExpression,
            32 => Self::PathPattern,
            33 => Self::PathMode,
            34 => Self::PathQuantifier,
            35 => Self::OptionalMatchClause,
            36 => Self::ListExpression,
            37 => Self::ByteStringLiteralExpression,
            38 => Self::TemporalLiteralExpression,
            39 => Self::DurationLiteralExpression,
            40 => Self::RecordExpression,
            41 => Self::RecordEntry,
            42 => Self::SubscriptExpression,
            43 => Self::ProjectionAlias,
            44 => Self::UnionClause,
            45 => Self::LimitClause,
            46 => Self::OrderByClause,
            47 => Self::OffsetClause,
            48 => Self::GroupByClause,
            49 => Self::CaseExpression,
            50 => Self::CaseWhenClause,
            51 => Self::CaseElseClause,
            52 => Self::CreateSchemaStatement,
            53 => Self::DropSchemaStatement,
            54 => Self::CreateGraphStatement,
            55 => Self::DropGraphStatement,
            56 => Self::CreateGraphTypeStatement,
            57 => Self::DropGraphTypeStatement,
            58 => Self::CatalogObjectName,
            59 => Self::CatalogConflictClause,
            60 => Self::GraphTypeSource,
            61 => Self::NestedGraphTypeSpecification,
            62 => Self::NodeTypeSpecification,
            63 => Self::EdgeTypeSpecification,
            64 => Self::EdgeKind,
            65 => Self::EndpointPair,
            66 => Self::NodeTypeReference,
            67 => Self::EdgeDirection,
            68 => Self::KeyLabelSet,
            69 => Self::LabelSetPhrase,
            70 => Self::PropertyTypeList,
            71 => Self::PropertyType,
            72 => Self::PropertyValueType,
            73 => Self::ValueTypeAtom,
            74 => Self::ReferenceValueType,
            75 => Self::TypeParameterList,
            76 => Self::FieldTypeList,
            77 => Self::FieldType,
            78 => Self::NotNullConstraint,
            79 => Self::InsertStatement,
            80 => Self::SetStatement,
            81 => Self::SetItem,
            82 => Self::RemoveStatement,
            83 => Self::RemoveItem,
            84 => Self::DeleteStatement,
            85 => Self::DeleteItem,
            86 => Self::CallStatement,
            87 => Self::ProcedureName,
            88 => Self::StartTransactionStatement,
            89 => Self::CommitStatement,
            90 => Self::RollbackStatement,
            91 => Self::SessionSetStatement,
            92 => Self::SessionResetStatement,
            93 => Self::SessionCloseStatement,
            94 => Self::InlineWhereClause,
            95 => Self::LabelPredicateExpression,
            96 => Self::LabelNameExpression,
            97 => Self::LabelWildcardExpression,
            98 => Self::LabelNotExpression,
            99 => Self::LabelAndExpression,
            100 => Self::LabelOrExpression,
            _ => Self::Unknown,
        }
    }
}
pub(crate) const GRAMMAR_SYNTAX_SHAPES: &[(&str, &str, &[&str])] = &[
    ("SourceFile", "node", &["query"]),
    ("Query", "node", &["clause"]),
    ("MatchClause", "node", &["mode", "patterns"]),
    ("WhereClause", "node", &["expression"]),
    ("LetClause", "node", &["binding"]),
    ("LetBinding", "node", &["name", "value"]),
    ("ReturnClause", "node", &["projection"]),
    ("GraphPattern", "node", &["element"]),
    ("GraphPatternList", "node", &["pattern"]),
    (
        "NodePattern",
        "node",
        &["binding", "labels", "properties", "predicate"],
    ),
    ("PropertyMap", "node", &["entry"]),
    ("PropertyEntry", "node", &["key", "value"]),
    (
        "EdgePattern",
        "node",
        &[
            "direction",
            "binding",
            "labels",
            "properties",
            "predicate",
            "quantifier",
        ],
    ),
    ("LabelList", "node", &["label"]),
    ("Expression", "node", &["token"]),
    ("NameExpression", "node", &["name"]),
    ("LiteralExpression", "node", &["literal"]),
    (
        "CharacterStringLiteralExpression",
        "node",
        &["value", "form", "no-escape"],
    ),
    ("UnaryExpression", "node", &["operator", "operand"]),
    ("BinaryExpression", "node", &["left", "operator", "right"]),
    ("ParenthesizedExpression", "node", &["expression"]),
    ("Keyword", "token", &["text"]),
    ("Identifier", "token", &["text"]),
    ("Number", "token", &["text"]),
    ("String", "token", &["text"]),
    ("ByteString", "token", &["text"]),
    ("Whitespace", "token", &["text"]),
    ("Punctuation", "token", &["text"]),
    ("Comment", "token", &["text"]),
    ("Unknown", "token", &["text"]),
    ("PropertyAccessExpression", "node", &["base", "property"]),
    ("FunctionCallExpression", "node", &["name", "argument"]),
    ("PathPattern", "node", &["binding", "pattern"]),
    ("PathMode", "node", &["kind"]),
    ("PathQuantifier", "node", &["minimum", "maximum"]),
    ("OptionalMatchClause", "node", &["match"]),
    ("ListExpression", "node", &["element"]),
    ("ByteStringLiteralExpression", "node", &["value"]),
    ("TemporalLiteralExpression", "node", &["qualifier", "value"]),
    ("DurationLiteralExpression", "node", &["value"]),
    ("RecordExpression", "node", &["entry"]),
    ("RecordEntry", "node", &["name", "value"]),
    ("SubscriptExpression", "node", &["base", "index"]),
    ("ProjectionAlias", "node", &["expression", "alias"]),
    ("UnionClause", "node", &["query"]),
    ("LimitClause", "node", &["limit"]),
    ("OrderByClause", "node", &["key", "direction"]),
    ("OffsetClause", "node", &["offset"]),
    ("GroupByClause", "node", &["key"]),
    (
        "CaseExpression",
        "node",
        &["operand", "branch", "else-result"],
    ),
    ("CaseWhenClause", "node", &["condition", "result"]),
    ("CaseElseClause", "node", &["result"]),
    ("CreateSchemaStatement", "node", &["name"]),
    ("DropSchemaStatement", "node", &["name"]),
    ("CreateGraphStatement", "node", &["name", "graph-type"]),
    ("DropGraphStatement", "node", &["name"]),
    (
        "CreateGraphTypeStatement",
        "node",
        &["name", "source", "policy"],
    ),
    ("DropGraphTypeStatement", "node", &["name", "policy"]),
    ("CatalogObjectName", "node", &["part"]),
    ("CatalogConflictClause", "node", &["kind"]),
    ("GraphTypeSource", "node", &["kind", "target"]),
    ("NestedGraphTypeSpecification", "node", &["element"]),
    (
        "NodeTypeSpecification",
        "node",
        &["name", "alias", "key-labels", "labels", "properties"],
    ),
    (
        "EdgeTypeSpecification",
        "node",
        &[
            "kind",
            "name",
            "endpoints",
            "direction",
            "key-labels",
            "labels",
            "properties",
        ],
    ),
    ("EdgeKind", "node", &["kind"]),
    ("EndpointPair", "node", &["endpoints", "direction"]),
    (
        "NodeTypeReference",
        "node",
        &["alias", "key-labels", "labels", "properties"],
    ),
    ("EdgeDirection", "node", &["kind"]),
    ("KeyLabelSet", "node", &["labels"]),
    ("LabelSetPhrase", "node", &["labels"]),
    ("PropertyTypeList", "node", &["property"]),
    ("PropertyType", "node", &["name", "marker", "value-type"]),
    (
        "PropertyValueType",
        "node",
        &["form", "item", "bound", "field", "nullability"],
    ),
    (
        "ValueTypeAtom",
        "node",
        &["kind", "parameter", "item", "field"],
    ),
    (
        "ReferenceValueType",
        "node",
        &["kind", "openness", "property", "specification", "field"],
    ),
    ("TypeParameterList", "node", &["value"]),
    ("FieldTypeList", "node", &["field"]),
    ("FieldType", "node", &["name", "marker", "value-type"]),
    ("NotNullConstraint", "node", &["kind"]),
    ("InsertStatement", "node", &["pattern"]),
    ("SetStatement", "node", &["item"]),
    ("SetItem", "node", &["target", "value"]),
    ("RemoveStatement", "node", &["item"]),
    ("RemoveItem", "node", &["target"]),
    ("DeleteStatement", "node", &["item", "detach"]),
    ("DeleteItem", "node", &["target"]),
    ("CallStatement", "node", &["call"]),
    ("ProcedureName", "node", &["part"]),
    ("StartTransactionStatement", "node", &["access-mode"]),
    ("CommitStatement", "node", &["action"]),
    ("RollbackStatement", "node", &["action"]),
    ("SessionSetStatement", "node", &["setting"]),
    ("SessionResetStatement", "node", &["setting"]),
    ("SessionCloseStatement", "node", &["action"]),
    ("InlineWhereClause", "node", &["expression"]),
    ("LabelPredicateExpression", "node", &["operand", "label"]),
    ("LabelNameExpression", "node", &["name"]),
    ("LabelWildcardExpression", "node", &["wildcard"]),
    ("LabelNotExpression", "node", &["operand"]),
    ("LabelAndExpression", "node", &["left", "right"]),
    ("LabelOrExpression", "node", &["left", "right"]),
];
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
/// Grammar-owned keyword identities.
pub enum Keyword {
    Match,
    Optional,
    Where,
    Let,
    Return,
    Or,
    Xor,
    And,
    Not,
    Call,
    Create,
    Drop,
    Insert,
    Delete,
    Set,
    Remove,
    True,
    False,
    Null,
    In,
    As,
    Union,
    Limit,
    Order,
    By,
    Group,
    Asc,
    Desc,
    Offset,
    Case,
    When,
    Then,
    Else,
    End,
    Schema,
    Session,
    Reset,
    Close,
    Property,
    Graph,
    Any,
    Typed,
    If,
    Exists,
    Replace,
    Type,
    Copy,
    Of,
    Like,
    Detach,
    Nodetach,
    Start,
    Transaction,
    Read,
    Only,
    Write,
    Commit,
    Rollback,
    Walk,
    Trail,
    Acyclic,
    Simple,
    Is,
    Labeled,
    Date,
    Time,
    Timestamp,
    Datetime,
    Duration,
    Record,
}
pub(crate) fn keyword(word: &str) -> Option<Keyword> {
    if word.bytes().any(|byte| byte.is_ascii_lowercase()) {
        let uppercase = word.to_ascii_uppercase();
        keyword_uppercase(&uppercase)
    } else {
        keyword_uppercase(word)
    }
}
fn keyword_uppercase(word: &str) -> Option<Keyword> {
    match word {
        "MATCH" => Some(Keyword::Match),
        "OPTIONAL" => Some(Keyword::Optional),
        "WHERE" => Some(Keyword::Where),
        "LET" => Some(Keyword::Let),
        "RETURN" => Some(Keyword::Return),
        "OR" => Some(Keyword::Or),
        "XOR" => Some(Keyword::Xor),
        "AND" => Some(Keyword::And),
        "NOT" => Some(Keyword::Not),
        "CALL" => Some(Keyword::Call),
        "CREATE" => Some(Keyword::Create),
        "DROP" => Some(Keyword::Drop),
        "INSERT" => Some(Keyword::Insert),
        "DELETE" => Some(Keyword::Delete),
        "SET" => Some(Keyword::Set),
        "REMOVE" => Some(Keyword::Remove),
        "TRUE" => Some(Keyword::True),
        "FALSE" => Some(Keyword::False),
        "NULL" => Some(Keyword::Null),
        "IN" => Some(Keyword::In),
        "AS" => Some(Keyword::As),
        "UNION" => Some(Keyword::Union),
        "LIMIT" => Some(Keyword::Limit),
        "ORDER" => Some(Keyword::Order),
        "BY" => Some(Keyword::By),
        "GROUP" => Some(Keyword::Group),
        "ASC" => Some(Keyword::Asc),
        "DESC" => Some(Keyword::Desc),
        "OFFSET" => Some(Keyword::Offset),
        "CASE" => Some(Keyword::Case),
        "WHEN" => Some(Keyword::When),
        "THEN" => Some(Keyword::Then),
        "ELSE" => Some(Keyword::Else),
        "END" => Some(Keyword::End),
        "SCHEMA" => Some(Keyword::Schema),
        "SESSION" => Some(Keyword::Session),
        "RESET" => Some(Keyword::Reset),
        "CLOSE" => Some(Keyword::Close),
        "PROPERTY" => Some(Keyword::Property),
        "GRAPH" => Some(Keyword::Graph),
        "ANY" => Some(Keyword::Any),
        "TYPED" => Some(Keyword::Typed),
        "IF" => Some(Keyword::If),
        "EXISTS" => Some(Keyword::Exists),
        "REPLACE" => Some(Keyword::Replace),
        "TYPE" => Some(Keyword::Type),
        "COPY" => Some(Keyword::Copy),
        "OF" => Some(Keyword::Of),
        "LIKE" => Some(Keyword::Like),
        "DETACH" => Some(Keyword::Detach),
        "NODETACH" => Some(Keyword::Nodetach),
        "START" => Some(Keyword::Start),
        "TRANSACTION" => Some(Keyword::Transaction),
        "READ" => Some(Keyword::Read),
        "ONLY" => Some(Keyword::Only),
        "WRITE" => Some(Keyword::Write),
        "COMMIT" => Some(Keyword::Commit),
        "ROLLBACK" => Some(Keyword::Rollback),
        "WALK" => Some(Keyword::Walk),
        "TRAIL" => Some(Keyword::Trail),
        "ACYCLIC" => Some(Keyword::Acyclic),
        "SIMPLE" => Some(Keyword::Simple),
        "IS" => Some(Keyword::Is),
        "LABELED" => Some(Keyword::Labeled),
        "DATE" => Some(Keyword::Date),
        "TIME" => Some(Keyword::Time),
        "TIMESTAMP" => Some(Keyword::Timestamp),
        "DATETIME" => Some(Keyword::Datetime),
        "DURATION" => Some(Keyword::Duration),
        "RECORD" => Some(Keyword::Record),
        _ => None,
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum GrammarParserAction {
    MatchClause,
    OptionalMatchClause,
    ReturnClause,
    WhereClause,
    LetClause,
    UnionClause,
    LimitClause,
    OrderByClause,
    OffsetClause,
    GroupByClause,
    CallStatement,
    CreateSchemaStatement,
    DropSchemaStatement,
    InsertStatement,
    DeleteStatement,
    SetStatement,
    RemoveStatement,
    StartTransactionStatement,
    CommitStatement,
    RollbackStatement,
    SessionSetStatement,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct GrammarParserEntrypoint {
    pub(crate) action: GrammarParserAction,
}
pub(crate) fn top_level_parser_entrypoint(keyword: Keyword) -> Option<GrammarParserEntrypoint> {
    match keyword {
        Keyword::Match => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::MatchClause,
        }),
        Keyword::Optional => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::OptionalMatchClause,
        }),
        Keyword::Return => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::ReturnClause,
        }),
        Keyword::Where => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::WhereClause,
        }),
        Keyword::Let => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::LetClause,
        }),
        Keyword::Union => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::UnionClause,
        }),
        Keyword::Limit => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::LimitClause,
        }),
        Keyword::Order => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::OrderByClause,
        }),
        Keyword::Offset => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::OffsetClause,
        }),
        Keyword::Group => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::GroupByClause,
        }),
        Keyword::Call => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::CallStatement,
        }),
        Keyword::Create => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::CreateSchemaStatement,
        }),
        Keyword::Drop => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::DropSchemaStatement,
        }),
        Keyword::Insert => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::InsertStatement,
        }),
        Keyword::Delete => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::DeleteStatement,
        }),
        Keyword::Set => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::SetStatement,
        }),
        Keyword::Remove => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::RemoveStatement,
        }),
        Keyword::Detach => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::DeleteStatement,
        }),
        Keyword::Nodetach => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::DeleteStatement,
        }),
        Keyword::Start => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::StartTransactionStatement,
        }),
        Keyword::Commit => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::CommitStatement,
        }),
        Keyword::Rollback => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::RollbackStatement,
        }),
        Keyword::Session => Some(GrammarParserEntrypoint {
            action: GrammarParserAction::SessionSetStatement,
        }),
        _ => None,
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct BinaryOperatorSpec {
    pub(crate) left_binding_power: u8,
    pub(crate) right_binding_power: u8,
    pub(crate) is_right_associative: bool,
    pub(crate) width: u8,
}
pub(crate) fn binary_operator_spec(
    first: TokenKind,
    second: Option<TokenKind>,
) -> Option<BinaryOperatorSpec> {
    match (first, second) {
        (TokenKind::Punctuation('<'), Some(TokenKind::Punctuation('>'))) => {
            Some(BinaryOperatorSpec {
                left_binding_power: 30,
                right_binding_power: 31,
                is_right_associative: false,
                width: 2,
            })
        }
        (TokenKind::Punctuation('<'), Some(TokenKind::Punctuation('='))) => {
            Some(BinaryOperatorSpec {
                left_binding_power: 30,
                right_binding_power: 31,
                is_right_associative: false,
                width: 2,
            })
        }
        (TokenKind::Punctuation('>'), Some(TokenKind::Punctuation('='))) => {
            Some(BinaryOperatorSpec {
                left_binding_power: 30,
                right_binding_power: 31,
                is_right_associative: false,
                width: 2,
            })
        }
        (TokenKind::Punctuation('|'), Some(TokenKind::Punctuation('|'))) => {
            Some(BinaryOperatorSpec {
                left_binding_power: 35,
                right_binding_power: 36,
                is_right_associative: false,
                width: 2,
            })
        }
        (TokenKind::Keyword(Keyword::Or), _) => Some(BinaryOperatorSpec {
            left_binding_power: 10,
            right_binding_power: 11,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Keyword(Keyword::Xor), _) => Some(BinaryOperatorSpec {
            left_binding_power: 15,
            right_binding_power: 16,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Keyword(Keyword::And), _) => Some(BinaryOperatorSpec {
            left_binding_power: 20,
            right_binding_power: 21,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Keyword(Keyword::In), _) => Some(BinaryOperatorSpec {
            left_binding_power: 30,
            right_binding_power: 31,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('='), _) => Some(BinaryOperatorSpec {
            left_binding_power: 30,
            right_binding_power: 31,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('<'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 30,
            right_binding_power: 31,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('>'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 30,
            right_binding_power: 31,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('+'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 40,
            right_binding_power: 41,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('-'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 40,
            right_binding_power: 41,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('*'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 50,
            right_binding_power: 51,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('/'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 50,
            right_binding_power: 51,
            is_right_associative: false,
            width: 1,
        }),
        (TokenKind::Punctuation('%'), _) => Some(BinaryOperatorSpec {
            left_binding_power: 50,
            right_binding_power: 51,
            is_right_associative: false,
            width: 1,
        }),
        _ => None,
    }
}
pub(crate) fn prefix_operator_precedence(kind: TokenKind) -> Option<u8> {
    match kind {
        TokenKind::Keyword(Keyword::Not) => Some(25),
        TokenKind::Punctuation('+') => Some(60),
        TokenKind::Punctuation('-') => Some(60),
        _ => None,
    }
}
#[rustfmt::skip]
pub(crate) const GRAMMAR_RECOVERIES: &[(&str, &str, &str)] = &[
    ("block-comment", "GQL-SYNTAX-UNTERMINATED-BLOCK-COMMENT", "preserve-source"),
    ("numeric-literal", "GQL-SYNTAX-INVALID-NUMERIC-LITERAL", "preserve-source"),
    ("integer-literal-range", "GQL-SYNTAX-NUMERIC-LITERAL-OUT-OF-RANGE", "preserve-source"),
    ("edge-label-separator", "GQL-PARSE-EDGE-LABEL-SEPARATOR", "preserve-source"),
    ("create-schema", "GQL-PARSE-CREATE-SCHEMA-SYNTAX", "preserve-source"),
    ("drop-schema", "GQL-PARSE-DROP-SCHEMA-SYNTAX", "preserve-source"),
    ("create-graph", "GQL-PARSE-CREATE-GRAPH-SYNTAX", "preserve-source"),
    ("drop-graph", "GQL-PARSE-DROP-GRAPH-SYNTAX", "preserve-source"),
    ("create-graph-type", "GQL-PARSE-CREATE-GRAPH-TYPE-SYNTAX", "preserve-source"),
    ("nested-graph-type", "GQL-PARSE-NESTED-GRAPH-TYPE-SYNTAX", "preserve-source"),
    ("drop-graph-type", "GQL-PARSE-DROP-GRAPH-TYPE-SYNTAX", "preserve-source"),
    ("insert-statement", "GQL-PARSE-INSERT-SYNTAX", "preserve-source"),
    ("set-statement", "GQL-PARSE-SET-SYNTAX", "preserve-source"),
    ("remove-statement", "GQL-PARSE-REMOVE-SYNTAX", "preserve-source"),
    ("delete-statement", "GQL-PARSE-DELETE-SYNTAX", "preserve-source"),
    ("call-statement", "GQL-PARSE-CALL-SYNTAX", "preserve-source"),
    ("transaction-command", "GQL-PARSE-TRANSACTION-SYNTAX", "preserve-source"),
    ("session-command", "GQL-PARSE-SESSION-COMMAND-SYNTAX", "preserve-source"),
    ("inline-node-where", "GQL-PARSE-INLINE-WHERE-SYNTAX", "preserve-source"),
    ("inline-edge-where", "GQL-PARSE-INLINE-WHERE-SYNTAX", "preserve-source"),
    ("path-mode", "GQL-PARSE-PATH-MODE-SYNTAX", "preserve-source"),
    ("path-quantifier", "GQL-PARSE-PATH-QUANTIFIER", "preserve-source"),
    ("string-literal", "GQL-SYNTAX-UNTERMINATED-STRING", "preserve-source"),
    ("character-string-literal", "GQL-SYNTAX-INVALID-CHARACTER-STRING-LITERAL", "preserve-source"),
    ("byte-string-literal", "GQL-SYNTAX-INVALID-BYTE-STRING", "preserve-source"),
    ("temporal-literal", "GQL-SYNTAX-INVALID-TEMPORAL-LITERAL", "preserve-source"),
    ("duration-literal", "GQL-SYNTAX-INVALID-DURATION-LITERAL", "preserve-source"),
    ("list-literal", "GQL-PARSE-LIST-SYNTAX", "preserve-source"),
    ("record-literal", "GQL-PARSE-RECORD-SYNTAX", "preserve-source"),
    ("delimited-identifier", "GQL-SYNTAX-UNTERMINATED-DELIMITED-IDENTIFIER", "preserve-source"),
    ("identifier-escape", "GQL-SYNTAX-INVALID-IDENTIFIER-ESCAPE", "preserve-source"),
    ("binding-variable", "GQL-PARSE-BINDING-VARIABLE-SYNTAX", "preserve-source"),
    ("unsupported-statement", "GQL-PARSE-UNSUPPORTED-STATEMENT", "preserve-source"),
    ("unsupported-keyword-expression", "GQL-PARSE-UNSUPPORTED-KEYWORD-EXPRESSION", "preserve-source"),
    ("non-iso-operator", "GQL-PARSE-NON-ISO-OPERATOR", "preserve-source"),
    ("label-expression", "GQL-PARSE-LABEL-EXPRESSION", "preserve-source"),
    ("match-pattern-list", "GQL-PARSE-MATCH-PATTERN-LIST", "preserve-source"),
    ("optional-match", "GQL-PARSE-OPTIONAL-MATCH-SYNTAX", "preserve-source"),
    ("where-clause", "GQL-PARSE-WHERE-SYNTAX", "preserve-source"),
    ("union-clause", "GQL-PARSE-UNION-SYNTAX", "preserve-source"),
    ("expression-syntax", "GQL-PARSE-EXPRESSION-SYNTAX", "preserve-source"),
];
pub(crate) fn recovery_diagnostic(site: &str) -> Option<&'static str> {
    GRAMMAR_RECOVERIES
        .iter()
        .find_map(|(candidate, code, _)| (*candidate == site).then_some(*code))
}
