-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mrr_agentic_ai_context]: function definitions
module
public import Aeneas
public import ValueGenerated.Types
public import ValueGenerated.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

local infixr:35 " ** " => Prod

namespace MRR.ContextValue

/-- [core::option::{impl core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}::eq]:
    Source: '/rustc/library/core/src/option.rs', lines 2441:4-2441:38
    Name pattern: [core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq"]
def core.option.Option.Insts.CoreCmpPartialEqOption.eq
  {T : Type} (cmpPartialEqInst : core.cmp.PartialEq T T) (self : Option T)
  (other : Option T) :
  Result Bool
  := do
  match self with
  | none => let other1 := read_discriminant other
            ok (other1 = 0#isize)
  | some l =>
    match other with
    | none => ok false
    | some r => cmpPartialEqInst.eq l r

/-- Trait implementation: [core::option::{impl core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 2439:0-2439:56
    Name pattern: [core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>"]
impl_def core.option.Option.Insts.CoreCmpPartialEqOption {T : Type}
  (cmpPartialEqInst : core.cmp.PartialEq T T) : core.cmp.PartialEq (Option T)
  (Option T) := {
  eq := core.option.Option.Insts.CoreCmpPartialEqOption.eq cmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (core.option.Option.Insts.CoreCmpPartialEqOption cmpPartialEqInst)
}

/-- Trait implementation: [alloc::string::{impl core::cmp::PartialEq<alloc::string::String> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [core::cmp::PartialEq<alloc::string::String, alloc::string::String>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloc::string::String, alloc::string::String>"]
impl_def alloc.string.String.Insts.CoreCmpPartialEqString : core.cmp.PartialEq
  String String := {
  eq := alloc.string.String.Insts.CoreCmpPartialEqString.eq
  ne := core.cmp.PartialEq.ne.trait_default
    alloc.string.String.Insts.CoreCmpPartialEqString
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::FactId> for mrr_identity::api::FactId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::FactId, mrr_identity::api::FactId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::FactId, mrr_identity::api::FactId>}::eq"]
def mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId.eq
  (self : mrr_identity.api.FactId) (other : mrr_identity.api.FactId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::FactId> for mrr_identity::api::FactId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::FactId, mrr_identity::api::FactId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::FactId, mrr_identity::api::FactId>"]
impl_def mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId :
  core.cmp.PartialEq mrr_identity.api.FactId mrr_identity.api.FactId := {
  eq := mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::EntityId> for mrr_identity::api::EntityId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>}::eq"]
def mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq
  (self : mrr_identity.api.EntityId) (other : mrr_identity.api.EntityId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::EntityId> for mrr_identity::api::EntityId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>"]
impl_def mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId :
  core.cmp.PartialEq mrr_identity.api.EntityId mrr_identity.api.EntityId := {
  eq := mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::RuleId> for mrr_identity::api::RuleId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RuleId, mrr_identity::api::RuleId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RuleId, mrr_identity::api::RuleId>}::eq"]
def mrr_identity.api.RuleId.Insts.CoreCmpPartialEqRuleId.eq
  (self : mrr_identity.api.RuleId) (other : mrr_identity.api.RuleId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::RuleId> for mrr_identity::api::RuleId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::RuleId, mrr_identity::api::RuleId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::RuleId, mrr_identity::api::RuleId>"]
impl_def mrr_identity.api.RuleId.Insts.CoreCmpPartialEqRuleId :
  core.cmp.PartialEq mrr_identity.api.RuleId mrr_identity.api.RuleId := {
  eq := mrr_identity.api.RuleId.Insts.CoreCmpPartialEqRuleId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_identity.api.RuleId.Insts.CoreCmpPartialEqRuleId
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::RulePackId> for mrr_identity::api::RulePackId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RulePackId, mrr_identity::api::RulePackId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RulePackId, mrr_identity::api::RulePackId>}::eq"]
def mrr_identity.api.RulePackId.Insts.CoreCmpPartialEqRulePackId.eq
  (self : mrr_identity.api.RulePackId) (other : mrr_identity.api.RulePackId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::RulePackId> for mrr_identity::api::RulePackId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::RulePackId, mrr_identity::api::RulePackId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::RulePackId, mrr_identity::api::RulePackId>"]
impl_def mrr_identity.api.RulePackId.Insts.CoreCmpPartialEqRulePackId :
  core.cmp.PartialEq mrr_identity.api.RulePackId mrr_identity.api.RulePackId
  := {
  eq := mrr_identity.api.RulePackId.Insts.CoreCmpPartialEqRulePackId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_identity.api.RulePackId.Insts.CoreCmpPartialEqRulePackId
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::DerivationId> for mrr_identity::api::DerivationId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::DerivationId, mrr_identity::api::DerivationId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::DerivationId, mrr_identity::api::DerivationId>}::eq"]
def mrr_identity.api.DerivationId.Insts.CoreCmpPartialEqDerivationId.eq
  (self : mrr_identity.api.DerivationId)
  (other : mrr_identity.api.DerivationId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::DerivationId> for mrr_identity::api::DerivationId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::DerivationId, mrr_identity::api::DerivationId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::DerivationId, mrr_identity::api::DerivationId>"]
impl_def mrr_identity.api.DerivationId.Insts.CoreCmpPartialEqDerivationId :
  core.cmp.PartialEq mrr_identity.api.DerivationId
  mrr_identity.api.DerivationId := {
  eq := mrr_identity.api.DerivationId.Insts.CoreCmpPartialEqDerivationId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_identity.api.DerivationId.Insts.CoreCmpPartialEqDerivationId
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::RelationId> for mrr_identity::api::RelationId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RelationId, mrr_identity::api::RelationId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::RelationId, mrr_identity::api::RelationId>}::eq"]
def mrr_identity.api.RelationId.Insts.CoreCmpPartialEqRelationId.eq
  (self : mrr_identity.api.RelationId) (other : mrr_identity.api.RelationId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::GenerationId> for mrr_identity::api::GenerationId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::GenerationId, mrr_identity::api::GenerationId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::GenerationId, mrr_identity::api::GenerationId>}::eq"]
def mrr_identity.api.GenerationId.Insts.CoreCmpPartialEqGenerationId.eq
  (self : mrr_identity.api.GenerationId)
  (other : mrr_identity.api.GenerationId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

mutual

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::Value> for mrr_relation::api::Value}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 38:4-38:38
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::Value, mrr_relation::api::Value>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::Value, mrr_relation::api::Value>}::eq"]
def mrr_relation.api.Value.Insts.CoreCmpPartialEqValue.eq
  (self : mrr_relation.api.Value) (other : mrr_relation.api.Value) :
  Result Bool
  := do
  match self with
  | mrr_relation.api.Value.Entity left =>
    match other with
    | mrr_relation.api.Value.Entity right =>
      mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq left right
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Null =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok true
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Boolean left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean right =>
      core.cmp.impls.PartialEqBool.eq left right
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Integer left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer right =>
      lift (core.cmp.impls.PartialEqI64.eq left right)
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Decimal left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Float left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.String left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.ByteString left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString right =>
      alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 left right
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Date left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Time left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Timestamp left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Duration left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.List left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List right =>
      let s := alloc.vec.Vec.deref left
      let s1 := alloc.vec.Vec.deref right
      mrr_relation.api.equal_value_lists s s1
    | mrr_relation.api.Value.Record _ => ok false
  | mrr_relation.api.Value.Record left =>
    match other with
    | mrr_relation.api.Value.Entity _ => ok false
    | mrr_relation.api.Value.Null => ok false
    | mrr_relation.api.Value.Boolean _ => ok false
    | mrr_relation.api.Value.Integer _ => ok false
    | mrr_relation.api.Value.Decimal _ => ok false
    | mrr_relation.api.Value.Float _ => ok false
    | mrr_relation.api.Value.String _ => ok false
    | mrr_relation.api.Value.ByteString _ => ok false
    | mrr_relation.api.Value.Date _ => ok false
    | mrr_relation.api.Value.Time _ => ok false
    | mrr_relation.api.Value.Timestamp _ => ok false
    | mrr_relation.api.Value.Duration _ => ok false
    | mrr_relation.api.Value.List _ => ok false
    | mrr_relation.api.Value.Record right =>
      let s := alloc.vec.Vec.deref left
      let s1 := alloc.vec.Vec.deref right
      mrr_relation.api.equal_value_records s s1
partial_fixpoint

/-- [mrr_relation::api::equal_value_lists]: loop 0:
    Source: 'crates/mrr-relation/src/api.rs', lines 103:4-106:5
    Name pattern: [mrr_relation::api::equal_value_lists] -/
@[rust_loop, rust_fun "mrr_relation::api::equal_value_lists"]
def mrr_relation.api.equal_value_lists_loop
  (left : Slice mrr_relation.api.Value) (right : Slice mrr_relation.api.Value)
  (index : Std.Usize) (equal : Bool) :
  Result Bool
  := do
  let i := Slice.len left
  if index < i
  then
    if equal
    then
      let v <- Slice.index_usize left index
      let v1 <- Slice.index_usize right index
      let equal1 <- mrr_relation.api.Value.Insts.CoreCmpPartialEqValue.eq v v1
      let index1 <- index + 1#usize
      mrr_relation.api.equal_value_lists_loop left right index1 equal1
    else ok equal
  else ok equal
partial_fixpoint

/-- [mrr_relation::api::equal_value_lists]:
    Source: 'crates/mrr-relation/src/api.rs', lines 97:0-97:61
    Name pattern: [mrr_relation::api::equal_value_lists] -/
@[rust_fun "mrr_relation::api::equal_value_lists"]
def mrr_relation.api.equal_value_lists
  (left : Slice mrr_relation.api.Value) (right : Slice mrr_relation.api.Value)
  :
  Result Bool
  := do
  let i := Slice.len left
  let i1 := Slice.len right
  if i != i1
  then ok false
  else mrr_relation.api.equal_value_lists_loop left right 0#usize true
partial_fixpoint

/-- [mrr_relation::api::equal_value_records]: loop 0:
    Source: 'crates/mrr-relation/src/api.rs', lines 116:4-124:5
    Name pattern: [mrr_relation::api::equal_value_records] -/
@[rust_loop, rust_fun "mrr_relation::api::equal_value_records"]
def mrr_relation.api.equal_value_records_loop
  (left : Slice (String ** mrr_relation.api.Value))
  (right : Slice (String ** mrr_relation.api.Value)) (index : Std.Usize)
  (equal : Bool) :
  Result Bool
  := do
  let i := Slice.len left
  if index < i
  then
    if equal
    then
      let (s, v) <- Slice.index_usize left index
      let (s1, v1) <- Slice.index_usize right index
      let equal1 <- mrr_relation.api.equal_record_fields s s1 v v1
      let index1 <- index + 1#usize
      mrr_relation.api.equal_value_records_loop left right index1 equal1
    else ok equal
  else ok equal
partial_fixpoint

/-- [mrr_relation::api::equal_value_records]:
    Source: 'crates/mrr-relation/src/api.rs', lines 110:0-110:83
    Name pattern: [mrr_relation::api::equal_value_records] -/
@[rust_fun "mrr_relation::api::equal_value_records"]
def mrr_relation.api.equal_value_records
  (left : Slice (String ** mrr_relation.api.Value))
  (right : Slice (String ** mrr_relation.api.Value)) :
  Result Bool
  := do
  let i := Slice.len left
  let i1 := Slice.len right
  if i != i1
  then ok false
  else mrr_relation.api.equal_value_records_loop left right 0#usize true
partial_fixpoint

/-- [mrr_relation::api::equal_record_fields]:
    Source: 'crates/mrr-relation/src/api.rs', lines 128:0-128:98
    Name pattern: [mrr_relation::api::equal_record_fields] -/
@[rust_fun "mrr_relation::api::equal_record_fields"]
def mrr_relation.api.equal_record_fields
  (left_key : String) (right_key : String) (left : mrr_relation.api.Value)
  (right : mrr_relation.api.Value) :
  Result Bool
  := do
  let b <-
    alloc.string.String.Insts.CoreCmpPartialEqString.eq left_key right_key
  if b
  then mrr_relation.api.Value.Insts.CoreCmpPartialEqValue.eq left right
  else ok false
partial_fixpoint

end

/-- Trait implementation: [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::Value> for mrr_relation::api::Value}]
    Source: 'crates/mrr-relation/src/api.rs', lines 37:0-37:24
    Name pattern: [core::cmp::PartialEq<mrr_relation::api::Value, mrr_relation::api::Value>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_relation::api::Value, mrr_relation::api::Value>"]
impl_def mrr_relation.api.Value.Insts.CoreCmpPartialEqValue :
  core.cmp.PartialEq mrr_relation.api.Value mrr_relation.api.Value := {
  eq := mrr_relation.api.Value.Insts.CoreCmpPartialEqValue.eq
  ne := core.cmp.PartialEq.ne.trait_default
    mrr_relation.api.Value.Insts.CoreCmpPartialEqValue
}

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::RelationAuthority> for mrr_relation::api::RelationAuthority}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 349:52-349:61
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::RelationAuthority, mrr_relation::api::RelationAuthority>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::RelationAuthority, mrr_relation::api::RelationAuthority>}::eq"]
def
  mrr_relation.api.RelationAuthority.Insts.CoreCmpPartialEqRelationAuthority.eq
  (self : mrr_relation.api.RelationAuthority)
  (other : mrr_relation.api.RelationAuthority) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | mrr_relation.api.RelationAuthority.Entity __self_0 =>
      match other with
      | mrr_relation.api.RelationAuthority.Entity __arg1_0 =>
        mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq __self_0
          __arg1_0
      | mrr_relation.api.RelationAuthority.Rule _ => fail panic
      | mrr_relation.api.RelationAuthority.RulePack _ => fail panic
    | mrr_relation.api.RelationAuthority.Rule __self_0 =>
      match other with
      | mrr_relation.api.RelationAuthority.Entity _ => fail panic
      | mrr_relation.api.RelationAuthority.Rule __arg1_0 =>
        mrr_identity.api.RuleId.Insts.CoreCmpPartialEqRuleId.eq __self_0
          __arg1_0
      | mrr_relation.api.RelationAuthority.RulePack _ => fail panic
    | mrr_relation.api.RelationAuthority.RulePack __self_0 =>
      match other with
      | mrr_relation.api.RelationAuthority.Entity _ => fail panic
      | mrr_relation.api.RelationAuthority.Rule _ => fail panic
      | mrr_relation.api.RelationAuthority.RulePack __arg1_0 =>
        mrr_identity.api.RulePackId.Insts.CoreCmpPartialEqRulePackId.eq
          __self_0 __arg1_0
  else ok false

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::FactProvenance> for mrr_relation::api::FactProvenance}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 356:52-356:61
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::FactProvenance, mrr_relation::api::FactProvenance>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::FactProvenance, mrr_relation::api::FactProvenance>}::eq"]
def mrr_relation.api.FactProvenance.Insts.CoreCmpPartialEqFactProvenance.eq
  (self : mrr_relation.api.FactProvenance)
  (other : mrr_relation.api.FactProvenance) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | mrr_relation.api.FactProvenance.Source __self_0 =>
      match other with
      | mrr_relation.api.FactProvenance.Source __arg1_0 =>
        mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq __self_0
          __arg1_0
      | mrr_relation.api.FactProvenance.Derivation _ => fail panic
    | mrr_relation.api.FactProvenance.Derivation __self_0 =>
      match other with
      | mrr_relation.api.FactProvenance.Source _ => fail panic
      | mrr_relation.api.FactProvenance.Derivation __arg1_0 =>
        mrr_identity.api.DerivationId.Insts.CoreCmpPartialEqDerivationId.eq
          __self_0 __arg1_0
  else ok false

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::EvidenceCompleteness> for mrr_relation::api::EvidenceCompleteness}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 362:52-362:61
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::EvidenceCompleteness, mrr_relation::api::EvidenceCompleteness>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::EvidenceCompleteness, mrr_relation::api::EvidenceCompleteness>}::eq"]
def
  mrr_relation.api.EvidenceCompleteness.Insts.CoreCmpPartialEqEvidenceCompleteness.eq
  (self : mrr_relation.api.EvidenceCompleteness)
  (other : mrr_relation.api.EvidenceCompleteness) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::FactValidity> for mrr_relation::api::FactValidity}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 369:52-369:61
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::FactValidity, mrr_relation::api::FactValidity>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::FactValidity, mrr_relation::api::FactValidity>}::eq"]
def mrr_relation.api.FactValidity.Insts.CoreCmpPartialEqFactValidity.eq
  (self : mrr_relation.api.FactValidity)
  (other : mrr_relation.api.FactValidity) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | mrr_relation.api.FactValidity.Valid => ok true
    | mrr_relation.api.FactValidity.InvalidatedBy __self_0 =>
      match other with
      | mrr_relation.api.FactValidity.Valid => ok true
      | mrr_relation.api.FactValidity.InvalidatedBy __arg1_0 =>
        mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId.eq __self_0
          __arg1_0
  else ok false

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::RelationContext> for mrr_relation::api::RelationContext}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 375:52-375:61
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::RelationContext, mrr_relation::api::RelationContext>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::RelationContext, mrr_relation::api::RelationContext>}::eq"]
def mrr_relation.api.RelationContext.Insts.CoreCmpPartialEqRelationContext.eq
  (self : mrr_relation.api.RelationContext)
  (other : mrr_relation.api.RelationContext) :
  Result Bool
  := do
  let b <-
    mrr_identity.api.GenerationId.Insts.CoreCmpPartialEqGenerationId.eq
      self.generation other.generation
  if b
  then
    let b1 <-
      mrr_relation.api.RelationAuthority.Insts.CoreCmpPartialEqRelationAuthority.eq
        self.authority other.authority
    if b1
    then
      let b2 <-
        mrr_relation.api.FactProvenance.Insts.CoreCmpPartialEqFactProvenance.eq
          self.provenance other.provenance
      if b2
      then
        let b3 <-
          mrr_relation.api.EvidenceCompleteness.Insts.CoreCmpPartialEqEvidenceCompleteness.eq
            self.completeness other.completeness
        if b3
        then
          mrr_relation.api.FactValidity.Insts.CoreCmpPartialEqFactValidity.eq
            self.validity other.validity
        else ok false
      else ok false
    else ok false
  else ok false

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::Fact> for mrr_relation::api::Fact}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 453:40-453:49
    Name pattern: [mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::Fact, mrr_relation::api::Fact>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_relation::api::{core::cmp::PartialEq<mrr_relation::api::Fact, mrr_relation::api::Fact>}::eq"]
def mrr_relation.api.Fact.Insts.CoreCmpPartialEqFact.eq
  (self : mrr_relation.api.Fact) (other : mrr_relation.api.Fact) :
  Result Bool
  := do
  let b <-
    mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId.eq self.id other.id
  if b
  then
    let b1 <-
      mrr_identity.api.RelationId.Insts.CoreCmpPartialEqRelationId.eq
        self.relation other.relation
    if b1
    then
      let b2 <-
        alloc.vec.partial_eq.PartialEqVec.eq
          mrr_relation.api.Value.Insts.CoreCmpPartialEqValue self.values
          other.values
      if b2
      then
        mrr_relation.api.RelationContext.Insts.CoreCmpPartialEqRelationContext.eq
          self.context other.context
      else ok false
    else ok false
  else ok false

/-- [mrr_agentic_ai_context::state::{impl core::cmp::PartialEq<mrr_agentic_ai_context::state::AgenticAiContextElement> for mrr_agentic_ai_context::state::AgenticAiContextElement}::eq]:
    Source: 'crates/mrr-agentic-ai-context/src/state.rs', lines 18:27-18:36
    Visibility: public -/
def
  state.AgenticAiContextElement.Insts.CoreCmpPartialEqAgenticAiContextElement.eq
  (self : state.AgenticAiContextElement)
  (other : state.AgenticAiContextElement) :
  Result Bool
  := do
  let b <-
    mrr_relation.api.Fact.Insts.CoreCmpPartialEqFact.eq self.fact other.fact
  if b
  then
    alloc.vec.partial_eq.PartialEqVec.eq
      mrr_identity.api.FactId.Insts.CoreCmpPartialEqFactId self.dependencies
      other.dependencies
  else ok false

/-- Trait implementation: [mrr_agentic_ai_context::state::{impl core::cmp::PartialEq<mrr_agentic_ai_context::state::AgenticAiContextElement> for mrr_agentic_ai_context::state::AgenticAiContextElement}]
    Source: 'crates/mrr-agentic-ai-context/src/state.rs', lines 18:27-18:36 -/
@[reducible]
impl_def
  state.AgenticAiContextElement.Insts.CoreCmpPartialEqAgenticAiContextElement :
  core.cmp.PartialEq state.AgenticAiContextElement
  state.AgenticAiContextElement := {
  eq :=
    state.AgenticAiContextElement.Insts.CoreCmpPartialEqAgenticAiContextElement.eq
  ne := core.cmp.PartialEq.ne.trait_default
    state.AgenticAiContextElement.Insts.CoreCmpPartialEqAgenticAiContextElement
}

/-- [mrr_agentic_ai_context::state::revision_elements_differ]:
    Source: 'crates/mrr-agentic-ai-context/src/state.rs', lines 312:0-317:1 -/
def state.revision_elements_differ
  (old : Option state.AgenticAiContextElement)
  (new : Option state.AgenticAiContextElement) :
  Result Bool
  := do
  core.cmp.PartialEq.ne.trait_default
    (core.option.Option.Insts.CoreCmpPartialEqOption (core.cmp.PartialEqShared
    state.AgenticAiContextElement.Insts.CoreCmpPartialEqAgenticAiContextElement))
    old new

end MRR.ContextValue
