-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mrr_relation]: function definitions
module
public import Aeneas
public import ValueGenerated.Types
public import ValueGenerated.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

local infixr:35 " ** " => Prod

namespace MRR.ContextValue

/-- Trait implementation: [alloc::string::{impl core::cmp::PartialEq<alloc::string::String> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [core::cmp::PartialEq<alloc::string::String, alloc::string::String>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloc::string::String, alloc::string::String>"]
def alloc.string.String.Insts.CoreCmpPartialEqString : core.cmp.PartialEq
  String String := {
  eq := alloc.string.String.Insts.CoreCmpPartialEqString.eq
}

/-- [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::EntityId> for mrr_identity::api::EntityId}::eq]:
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>}::eq]
    Visibility: public -/
@[rust_fun
  "mrr_identity::api::{core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>}::eq"]
def mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq
  (self : mrr_identity.api.EntityId) (other : mrr_identity.api.EntityId) :
  Result Bool
  := do
  core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self other

/-- Trait implementation: [mrr_identity::api::{impl core::cmp::PartialEq<mrr_identity::api::EntityId> for mrr_identity::api::EntityId}]
    Source: 'crates/mrr-identity/src/api.rs', lines 175:45-175:54
    Name pattern: [core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<mrr_identity::api::EntityId, mrr_identity::api::EntityId>"]
def mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId :
  core.cmp.PartialEq mrr_identity.api.EntityId mrr_identity.api.EntityId := {
  eq := mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq
}

mutual

/-- [mrr_relation::api::{impl core::cmp::PartialEq<mrr_relation::api::Value> for mrr_relation::api::Value}::eq]:
    Source: 'crates/mrr-relation/src/api.rs', lines 38:4-94:5
    Visibility: public -/
def api.Value.Insts.CoreCmpPartialEqValue.eq
  (self : api.Value) (other : api.Value) : Result Bool := do
  match self with
  | api.Value.Entity left =>
    match other with
    | api.Value.Entity right =>
      mrr_identity.api.EntityId.Insts.CoreCmpPartialEqEntityId.eq left right
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Null =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok true
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Boolean left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean right => core.cmp.impls.PartialEqBool.eq left right
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Integer left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer right =>
      lift (core.cmp.impls.PartialEqI64.eq left right)
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Decimal left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Float left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.String left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.ByteString left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString right =>
      alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 left right
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Date left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Time left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Timestamp left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.Duration left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration right =>
      alloc.string.String.Insts.CoreCmpPartialEqString.eq left right
    | api.Value.List _ => ok false
    | api.Value.Record _ => ok false
  | api.Value.List left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List right =>
      let s := alloc.vec.Vec.deref left
      let s1 := alloc.vec.Vec.deref right
      api.equal_value_lists s s1
    | api.Value.Record _ => ok false
  | api.Value.Record left =>
    match other with
    | api.Value.Entity _ => ok false
    | api.Value.Null => ok false
    | api.Value.Boolean _ => ok false
    | api.Value.Integer _ => ok false
    | api.Value.Decimal _ => ok false
    | api.Value.Float _ => ok false
    | api.Value.String _ => ok false
    | api.Value.ByteString _ => ok false
    | api.Value.Date _ => ok false
    | api.Value.Time _ => ok false
    | api.Value.Timestamp _ => ok false
    | api.Value.Duration _ => ok false
    | api.Value.List _ => ok false
    | api.Value.Record right =>
      let s := alloc.vec.Vec.deref left
      let s1 := alloc.vec.Vec.deref right
      api.equal_value_records s s1
partial_fixpoint

/-- [mrr_relation::api::equal_value_lists]: loop 0:
    Source: 'crates/mrr-relation/src/api.rs', lines 103:4-106:5 -/
@[rust_loop]
def api.equal_value_lists_loop
  (left : Slice api.Value) (right : Slice api.Value) (index : Std.Usize)
  (equal : Bool) :
  Result Bool
  := do
  let i := Slice.len left
  if index < i
  then
    if equal
    then
      let v <- Slice.index_usize left index
      let v1 <- Slice.index_usize right index
      let equal1 <- api.Value.Insts.CoreCmpPartialEqValue.eq v v1
      let index1 <- index + 1#usize
      api.equal_value_lists_loop left right index1 equal1
    else ok equal
  else ok equal
partial_fixpoint

/-- [mrr_relation::api::equal_value_lists]:
    Source: 'crates/mrr-relation/src/api.rs', lines 97:0-108:1 -/
def api.equal_value_lists
  (left : Slice api.Value) (right : Slice api.Value) : Result Bool := do
  let i := Slice.len left
  let i1 := Slice.len right
  if i != i1
  then ok false
  else api.equal_value_lists_loop left right 0#usize true
partial_fixpoint

/-- [mrr_relation::api::equal_value_records]: loop 0:
    Source: 'crates/mrr-relation/src/api.rs', lines 116:4-124:5 -/
@[rust_loop]
def api.equal_value_records_loop
  (left : Slice (String ** api.Value)) (right : Slice (String ** api.Value))
  (index : Std.Usize) (equal : Bool) :
  Result Bool
  := do
  let i := Slice.len left
  if index < i
  then
    if equal
    then
      let (s, v) <- Slice.index_usize left index
      let (s1, v1) <- Slice.index_usize right index
      let equal1 <- api.equal_record_fields s s1 v v1
      let index1 <- index + 1#usize
      api.equal_value_records_loop left right index1 equal1
    else ok equal
  else ok equal
partial_fixpoint

/-- [mrr_relation::api::equal_value_records]:
    Source: 'crates/mrr-relation/src/api.rs', lines 110:0-126:1 -/
def api.equal_value_records
  (left : Slice (String ** api.Value)) (right : Slice (String ** api.Value)) :
  Result Bool
  := do
  let i := Slice.len left
  let i1 := Slice.len right
  if i != i1
  then ok false
  else api.equal_value_records_loop left right 0#usize true
partial_fixpoint

/-- [mrr_relation::api::equal_record_fields]:
    Source: 'crates/mrr-relation/src/api.rs', lines 128:0-130:1 -/
def api.equal_record_fields
  (left_key : String) (right_key : String) (left : api.Value)
  (right : api.Value) :
  Result Bool
  := do
  let b <-
    alloc.string.String.Insts.CoreCmpPartialEqString.eq left_key right_key
  if b
  then api.Value.Insts.CoreCmpPartialEqValue.eq left right
  else ok false
partial_fixpoint

end

end MRR.ContextValue
