-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mrr_agentic_ai_context]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

local infixr:35 " ** " => Prod

namespace MRR.ContextValue

/-- [mrr_identity::api::FactId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::FactId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::FactId"]
def mrr_identity.api.FactId := Array Std.U8 32#usize

/-- [mrr_identity::api::EntityId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::EntityId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::EntityId"]
def mrr_identity.api.EntityId := Array Std.U8 32#usize

/-- [mrr_identity::api::RuleId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::RuleId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::RuleId"]
def mrr_identity.api.RuleId := Array Std.U8 32#usize

/-- [mrr_identity::api::RulePackId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::RulePackId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::RulePackId"]
def mrr_identity.api.RulePackId := Array Std.U8 32#usize

/-- [mrr_identity::api::DerivationId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::DerivationId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::DerivationId"]
def mrr_identity.api.DerivationId := Array Std.U8 32#usize

/-- [mrr_identity::api::RelationId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::RelationId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::RelationId"]
def mrr_identity.api.RelationId := Array Std.U8 32#usize

/-- [mrr_identity::api::GenerationId]
    Source: 'crates/mrr-identity/src/api.rs', lines 176:8-176:45
    Name pattern: [mrr_identity::api::GenerationId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::GenerationId"]
def mrr_identity.api.GenerationId := Array Std.U8 32#usize

/-- [mrr_relation::api::Value]
    Source: 'crates/mrr-relation/src/api.rs', lines 17:0-17:14
    Name pattern: [mrr_relation::api::Value]
    Visibility: public -/
@[discriminant isize, rust_type "mrr_relation::api::Value"]
inductive mrr_relation.api.Value where
| Entity : mrr_identity.api.EntityId -> mrr_relation.api.Value
| Null : mrr_relation.api.Value
| Boolean : Bool -> mrr_relation.api.Value
| Integer : Std.I64 -> mrr_relation.api.Value
| Decimal : String -> mrr_relation.api.Value
| Float : String -> mrr_relation.api.Value
| String : String -> mrr_relation.api.Value
| ByteString : alloc.vec.Vec Std.U8 -> mrr_relation.api.Value
| Date : String -> mrr_relation.api.Value
| Time : String -> mrr_relation.api.Value
| Timestamp : String -> mrr_relation.api.Value
| Duration : String -> mrr_relation.api.Value
| List : alloc.vec.Vec mrr_relation.api.Value -> mrr_relation.api.Value
| Record :
  alloc.vec.Vec (String ** mrr_relation.api.Value) ->
  mrr_relation.api.Value

/-- [mrr_relation::api::RelationAuthority]
    Source: 'crates/mrr-relation/src/api.rs', lines 350:0-350:26
    Name pattern: [mrr_relation::api::RelationAuthority]
    Visibility: public -/
@[discriminant isize, rust_type "mrr_relation::api::RelationAuthority"]
inductive mrr_relation.api.RelationAuthority where
| Entity : mrr_identity.api.EntityId -> mrr_relation.api.RelationAuthority
| Rule : mrr_identity.api.RuleId -> mrr_relation.api.RelationAuthority
| RulePack : mrr_identity.api.RulePackId -> mrr_relation.api.RelationAuthority

/-- [mrr_relation::api::FactProvenance]
    Source: 'crates/mrr-relation/src/api.rs', lines 357:0-357:23
    Name pattern: [mrr_relation::api::FactProvenance]
    Visibility: public -/
@[discriminant isize, rust_type "mrr_relation::api::FactProvenance"]
inductive mrr_relation.api.FactProvenance where
| Source : mrr_identity.api.EntityId -> mrr_relation.api.FactProvenance
| Derivation :
  mrr_identity.api.DerivationId ->
  mrr_relation.api.FactProvenance

/-- [mrr_relation::api::EvidenceCompleteness]
    Source: 'crates/mrr-relation/src/api.rs', lines 363:0-363:29
    Name pattern: [mrr_relation::api::EvidenceCompleteness]
    Visibility: public -/
@[discriminant isize, rust_type "mrr_relation::api::EvidenceCompleteness"]
inductive mrr_relation.api.EvidenceCompleteness where
| Complete : mrr_relation.api.EvidenceCompleteness
| Partial : mrr_relation.api.EvidenceCompleteness
| Unknown : mrr_relation.api.EvidenceCompleteness

/-- [mrr_relation::api::FactValidity]
    Source: 'crates/mrr-relation/src/api.rs', lines 370:0-370:21
    Name pattern: [mrr_relation::api::FactValidity]
    Visibility: public -/
@[discriminant isize, rust_type "mrr_relation::api::FactValidity"]
inductive mrr_relation.api.FactValidity where
| Valid : mrr_relation.api.FactValidity
| InvalidatedBy : mrr_identity.api.FactId -> mrr_relation.api.FactValidity

/-- [mrr_relation::api::RelationContext]
    Source: 'crates/mrr-relation/src/api.rs', lines 376:0-376:26
    Name pattern: [mrr_relation::api::RelationContext]
    Visibility: public -/
@[rust_type "mrr_relation::api::RelationContext"]
structure mrr_relation.api.RelationContext where
  generation : mrr_identity.api.GenerationId
  authority : mrr_relation.api.RelationAuthority
  provenance : mrr_relation.api.FactProvenance
  completeness : mrr_relation.api.EvidenceCompleteness
  validity : mrr_relation.api.FactValidity

/-- [mrr_relation::api::Fact]
    Source: 'crates/mrr-relation/src/api.rs', lines 454:0-454:15
    Name pattern: [mrr_relation::api::Fact]
    Visibility: public -/
@[rust_type "mrr_relation::api::Fact"]
structure mrr_relation.api.Fact where
  id : mrr_identity.api.FactId
  relation : mrr_identity.api.RelationId
  values : alloc.vec.Vec mrr_relation.api.Value
  context : mrr_relation.api.RelationContext

/-- [mrr_agentic_ai_context::state::AgenticAiContextElement]
    Source: 'crates/mrr-agentic-ai-context/src/state.rs', lines 19:0-22:1
    Visibility: public -/
structure state.AgenticAiContextElement where
  fact : mrr_relation.api.Fact
  dependencies : alloc.vec.Vec mrr_identity.api.FactId

end MRR.ContextValue
