-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mrr_relation]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

local infixr:35 " ** " => Prod

namespace MRR.ContextValue

/-- [mrr_identity::api::EntityId]
    Source: 'crates/mrr-identity/src/api.rs', lines 174:8-174:45
    Name pattern: [mrr_identity::api::EntityId]
    Visibility: public -/
@[reducible, rust_type "mrr_identity::api::EntityId"]
def mrr_identity.api.EntityId := Array Std.U8 32#usize

/-- [mrr_relation::api::Value]
    Source: 'crates/mrr-relation/src/api.rs', lines 17:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive api.Value where
| Entity : mrr_identity.api.EntityId -> api.Value
| Null : api.Value
| Boolean : Bool -> api.Value
| Integer : Std.I64 -> api.Value
| Decimal : String -> api.Value
| Float : String -> api.Value
| String : String -> api.Value
| ByteString : alloc.vec.Vec Std.U8 -> api.Value
| Date : String -> api.Value
| Time : String -> api.Value
| Timestamp : String -> api.Value
| Duration : String -> api.Value
| List : alloc.vec.Vec api.Value -> api.Value
| Record : alloc.vec.Vec (String ** api.Value) -> api.Value

end MRR.ContextValue
