import Evidence
import Driver
import NativeFacts
import Stack
import Expansion
import Forward
import Reverse
import ReverseIndex
import ImpactWrapper
import Coverage
import Rejection
import DeclaredForward
import RevisionProjection
import BindingEquality
import TransformationTable
import Lean.Util.CollectAxioms
import Lean.Elab.Command

open Lean Elab Command

run_cmd do
  let environment <- getEnv
  let allowed := #[`propext, `Classical.choice, `Quot.sound]
  let required := #[
    `MRR.TransformationTableProofs.forward_exact,
    `MRR.TransformationTableProofs.solve_exact,
    `MRR.TransformationTableProofs.extract_exact,
    `MRR.TransformationTableProofs.solve_is_zero_answer_extraction,
    `MRR.TransformationTableProofs.missing_forward,
    `MRR.TransformationTableProofs.missing_source_extraction,
    `MRR.ContextRustProofs.admission_accepted_iff,
    `MRR.ContextRustProofs.invalid_evidence_rejected,
    `MRR.ContextRustProofs.required_incomplete_rejected,
    `MRR.ContextRustProofs.merge_refines_max,
    `MRR.ContextRustProofs.merge_commutative,
    `MRR.ContextRustProofs.merge_associative,
    `MRR.ContextRustProofs.complete_is_identity,
    `MRR.ContextRustProofs.extracted_driver_total_correctness,
    `MRR.ContextRustProofs.extracted_driver_preserves_invariant,
    `MRR.ContextRustProofs.extracted_driver_stop_exact,
    `MRR.ContextRustProofs.extracted_driver_graph_invariant_complete,
    `MRR.ContextRustProofs.extracted_driver_refines_graph,
    `MRR.ContextRustProofs.extracted_model_driver_total_correctness,
    `MRR.ContextRustProofs.extracted_scheduled_driver_total_correctness,
    `MRR.AgenticAIContext.scheduled_step_coverage,
    `MRR.AgenticAIContext.scheduled_step_invariant,
    `MRR.AgenticAIContext.scheduled_initial_invariant,
    `MRR.AgenticAIContext.scheduled_capacity_decreases,
    `MRR.AgenticAIContext.scheduled_finished_exact,
    `MRR.ContextRustProofs.number_bytes_injective,
    `MRR.ContextRustProofs.fact_model_id_injective,
    `MRR.ContextRustProofs.fact_model_id_equal_iff,
    `MRR.ContextRustProofs.native_fact_id_has_32_bytes,
    `MRR.ContextRustProofs.native_fact_id_equality_exact,
    `MRR.ContextRustProofs.native_fact_id_equality_refines_model,
    `MRR.ContextRustProofs.native_fact_context_exact,
    `MRR.ContextRustProofs.native_completeness_exact,
    `MRR.ContextRustProofs.native_validity_exact,
    `MRR.ContextRustProofs.native_validity_equality_exact,
    `MRR.ContextRustProofs.native_validity_admission_exact,
    `MRR.ContextRustProofs.native_fact_admission_exact,
    `MRR.ContextRustProofs.native_fact_accepted_iff,
    `MRR.ContextRustProofs.native_invalid_fact_rejected,
    `MRR.ContextRustProofs.projected_dependencies_exact,
    `MRR.ContextRustProofs.native_required_projection,
    `MRR.ContextRustProofs.identity_clone_exact,
    `MRR.ContextRustProofs.pop_identity_empty,
    `MRR.ContextRustProofs.pop_identity_nonempty,
    `MRR.ContextRustProofs.pop_identity_lifo,
    `MRR.ContextRustProofs.pop_identity_projects_pending,
    `MRR.ContextRustProofs.append_identities_exact,
    `MRR.ContextRustProofs.append_identities_projects_pending,
    `MRR.ContextRustProofs.initial_pending_exact,
    `MRR.ContextRustProofs.initial_pending_projects_roots,
    `MRR.ContextRustProofs.initial_pending_graph_invariant,
    `MRR.ContextRustProofs.expansion_missing_stops,
    `MRR.ContextRustProofs.expansion_invalid_stops,
    `MRR.ContextRustProofs.expansion_incomplete_stops,
    `MRR.ContextRustProofs.expansion_accepted_step,
    `MRR.ContextRustProofs.native_contains_exact,
    `MRR.ContextRustProofs.native_set_insert_exact,
    `MRR.ContextRustProofs.native_map_lookup_exact,
    `MRR.ContextRustProofs.selected_model_member,
    `MRR.ContextRustProofs.native_forward_empty,
    `MRR.ContextRustProofs.native_forward_duplicate,
    `MRR.ContextRustProofs.native_forward_accepted,
    `MRR.ContextRustProofs.native_forward_step_refines_graph,
    `MRR.ContextRustProofs.native_forward_advance_contract,
    `MRR.ContextRustProofs.native_forward_run_exact,
    `MRR.ContextRustProofs.native_impact_enqueue_exact,
    `MRR.ContextRustProofs.enqueue_model_members,
    `MRR.ContextRustProofs.enqueue_model_pending_members,
    `MRR.ContextRustProofs.enqueue_model_length_balance,
    `MRR.ContextRustProofs.enqueue_model_selected_nodup,
    `MRR.ContextRustProofs.native_reverse_lookup_exact,
    `MRR.ContextRustProofs.native_impact_empty,
    `MRR.ContextRustProofs.native_impact_step_exact,
    `MRR.ContextRustProofs.native_nodup_subset_length,
    `MRR.ContextRustProofs.native_impact_nonempty_preserves,
    `MRR.ContextRustProofs.native_impact_advance_contract,
    `MRR.ContextRustProofs.native_impact_run_exact,
    `MRR.ContextRustProofs.native_entry_cursor_returns,
    `MRR.ContextRustProofs.native_reverse_edge_exact,
    `MRR.ContextRustProofs.put_reverse_members,
    `MRR.ContextRustProofs.add_declared_members,
    `MRR.ContextRustProofs.index_declared_members,
    `MRR.ContextRustProofs.native_reverse_dependency_loop_exact,
    `MRR.ContextRustProofs.native_reverse_elements_loop_exact,
    `MRR.ContextRustProofs.native_reverse_add_exact,
    `MRR.ContextRustProofs.native_reverse_index_exact,
    `MRR.ContextRustProofs.put_reverse_values_unique,
    `MRR.ContextRustProofs.add_declared_values_unique,
    `MRR.ContextRustProofs.index_declared_values_unique,
    `MRR.ContextRustProofs.reverse_values_unique_neighbors,
    `MRR.ContextRustProofs.native_reverse_index_declared_union,
    `MRR.ContextRustProofs.native_reverse_graph_projection,
    `MRR.ContextRustProofs.native_impact_seed_invariant,
    `MRR.ContextRustProofs.native_declared_impact_run_exact,
    `MRR.ContextRustProofs.native_changed_clone_exact,
    `MRR.ContextRustProofs.native_changed_len_exact,
    `MRR.ContextRustProofs.native_impact_pending_loop_exact,
    `MRR.ContextRustProofs.native_declared_impact_wrapper_exact,
    `MRR.ContextRustProofs.native_evidence_rank_projection,
    `MRR.ContextRustProofs.native_forward_step_preserves_coverage,
    `MRR.ContextRustProofs.native_forward_run_coverage_exact,
    `MRR.ContextRustProofs.native_empty_coverage_invariant,
    `MRR.ContextRustProofs.native_forward_rejection_run_stop,
    `MRR.ContextRustProofs.native_forward_missing_run_stop,
    `MRR.ContextRustProofs.native_forward_invalid_run_stop,
    `MRR.ContextRustProofs.native_forward_incomplete_run_stop,
    `MRR.ContextRustProofs.native_owned_iterator_list_exact,
    `MRR.ContextRustProofs.native_owned_collect_exact,
    `MRR.ContextRustProofs.native_closure_seed_exact,
    `MRR.ContextRustProofs.model_nodup_subset_length,
    `MRR.ContextRustProofs.native_required_closure_wrapper_exact,
    `MRR.ContextRustProofs.native_required_closure_error_projection,
    `MRR.ContextRustProofs.native_rejected_step_exact,
    `MRR.ContextRustProofs.native_continuation_invariant,
    `MRR.ContextRustProofs.native_general_forward_step,
    `MRR.ContextRustProofs.native_general_forward_run_total,
    `MRR.ContextRustProofs.native_required_closure_wrapper_total,
    `MRR.ContextRustProofs.native_declared_graph_projection,
    `MRR.ContextRustProofs.native_declared_graph_members,
    `MRR.ContextRustProofs.native_declared_source_matches,
    `MRR.ContextRustProofs.native_declared_source_closed,
    `MRR.ContextRustProofs.native_required_closure_declared_total,
    `MRR.ContextRustProofs.insert_all_members,
    `MRR.ContextRustProofs.insert_all_unique,
    `MRR.ContextRustProofs.insert_all_length,
    `MRR.ContextRustProofs.native_borrowed_contains_exact,
    `MRR.ContextRustProofs.native_revision_source_loop_exact,
    `MRR.ContextRustProofs.native_revision_source_union,
    `MRR.ContextRustProofs.native_revision_selected_loop_exact,
    `MRR.ContextRustProofs.native_revision_reuse_loop_exact,
    `MRR.ContextRustProofs.native_revision_reusable_exact,
    `MRR.ContextRustProofs.native_list_equality_exact,
    `MRR.ContextRustProofs.native_vec_equality_exact,
    `MRR.ContextRustProofs.native_generation_equality_exact,
    `MRR.ContextRustProofs.native_entity_equality_exact,
    `MRR.ContextRustProofs.native_query_id_equality_exact,
    `MRR.ContextRustProofs.native_state_id_equality_exact,
    `MRR.ContextRustProofs.native_revision_id_equality_exact,
    `MRR.ContextRustProofs.native_byte_array_equality_exact,
    `MRR.ContextRustProofs.native_fact_vec_equality_exact,
    `MRR.ContextRustProofs.native_external_revision_equality_exact,
    `MRR.ContextRustProofs.native_revision_binding_equality_exact,
    `MRR.ContextRustProofs.native_revision_vec_equality_exact,
    `MRR.ContextRustProofs.native_snapshot_equality_exact,
    `MRR.ContextRustProofs.native_query_equality_exact,
    `MRR.ContextRustProofs.native_contract_equality_exact,
    `MRR.ContextRustProofs.native_revision_bindings_changed_exact]
  required.forM fun declarationName => do
    unless environment.contains declarationName do
      throwError "Missing source theorem: {declarationName}"
    let axioms <- collectAxioms declarationName
    axioms.forM fun axiomName => do
      unless allowed.contains axiomName do
        throwError "{declarationName} depends on disallowed axiom {axiomName}"
  logInfo m!"SOURCE-AXIOM-AUDIT-OK: {required.size} source-refinement declarations"
